classDiagram
class BaseGroupedDataLabels {
  <<interface>>
  from: DataLabelsFrom
  choices: SelectableList#60;DataLabel#60;string#62;#62;
  indexes?: SelectableList#60;MachineDropIndex#62;
}
BaseGroupedDataLabels <.. SelectableList~S, L~


class JSONHeavydynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;HeavydynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONHeavydynDropIndex#62;
}
JSONHeavydynGroupedDataLabels <.. SelectableList~S, L~


class HeavydynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;HeavydynDropIndex#62;
}
HeavydynGroupedDataLabels <.. SelectableList~S, L~
BaseGroupedDataLabels <|-- HeavydynGroupedDataLabels

class JSONMaxidynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;MaxidynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONMaxidynDropIndex#62;
}
JSONMaxidynGroupedDataLabels <.. SelectableList~S, L~


class MaxidynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;MaxidynDropIndex#62;
}
MaxidynGroupedDataLabels <.. SelectableList~S, L~
BaseGroupedDataLabels <|-- MaxidynGroupedDataLabels

class JSONMinidynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;MinidynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONMinidynDropIndex#62;
}
JSONMinidynGroupedDataLabels <.. SelectableList~S, L~


class MinidynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;MinidynDropIndex#62;
}
MinidynGroupedDataLabels <.. SelectableList~S, L~
BaseGroupedDataLabels <|-- MinidynGroupedDataLabels

class JSONMachineGroupedDataLabels {
  <<type>>
  | JSONHeavydynGroupedDataLabels   | JSONMaxidynGroupedDataLabels   | JSONMinidynGroupedDataLabels
}
JSONMachineGroupedDataLabels <.. JSONHeavydynGroupedDataLabels
JSONMachineGroupedDataLabels <.. JSONMaxidynGroupedDataLabels
JSONMachineGroupedDataLabels <.. JSONMinidynGroupedDataLabels


class MachineGroupedDataLabels {
  <<type>>
  | HeavydynGroupedDataLabels   | MaxidynGroupedDataLabels   | MinidynGroupedDataLabels
}
MachineGroupedDataLabels <.. HeavydynGroupedDataLabels
MachineGroupedDataLabels <.. MaxidynGroupedDataLabels
MachineGroupedDataLabels <.. MinidynGroupedDataLabels


class SelectableList~S, L~ {
  <<interface>>
  selected: S | null
  list: L[]
}



