image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

test-code:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

  script:
    - npx pnpm check
    - npx pnpm i --store=node_modules/.pnpm-store
    - npm run test

test-ts:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npx pnpm check
