image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npx pnpm i --store=node_modules/.pnpm-store
    - npx pnpm run build
    - npm run test
