image: node:latest

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

default:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

.git_config: &git_config
  - mkdir ~/.ssh/
  - ssh-keyscan $CI_SERVER_HOST > ~/.ssh/known_hosts
  - echo "${SSH_PUSH_KEY}" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config user.email "$user_mail"
  - git config user.name "$user_name"
  - git remote remove ssh_origin || true
  - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"

.git_tag: &git_tag
  - version=$(npx pnpm json -f package.json version)
  - git tag "$version"
  - git push --tags ssh_origin

stages:
  - dependencies
  - build
  - test-types
  - test-unit
  - test-e2e
  - version

dependencies:
  stage: dependencies
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pnpm i
  tags:
    - shared

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pnpm j b
  tags:
    - shared

test-types:
  stage: test-types
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pnpm j c
    - pnpm j lint-fix
  tags:
    - shared

test-unit:
  stage: test-unit
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pnpm j t
  tags:
    - shared

test-e2e:
  stage: test-e2e
  image: mcr.microsoft.com/playwright:v1.31.0-focal
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - pnpm j b
    - npx playwright install
    - pnpm j test-e2e
  tags:
    - shared

version:
  stage: version
  variables:
    BRANCH_NAME: 'prod'
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $BRANCH_NAME
      when: on_success
  before_script:
    - *git_config
  script:
    - pnpm install json --save-dev --store=node_modules/.pnpm-store
    - pnpm json -I -f package.json -e "const versionPart = this.version.split('.');this.version=versionPart[0] + '.' + versionPart[1] + '.' + (Number(versionPart[2]) + 1)"
    - git add package.json
    - git commit -m "update version [ci skip]"
    - git push ssh_origin HEAD:$CI_COMMIT_REF_NAME
  after_script:
    - *git_tag
