image: node:latest

.prepare-pnpm: &prepare-pnpm
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

.git_config: &git_config
  - mkdir ~/.ssh/
  - ssh-keyscan $CI_SERVER_HOST > ~/.ssh/known_hosts
  - echo "${SSH_PUSH_KEY}" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config user.email "$user_mail"
  - git config user.name "$user_name"
  - git remote remove ssh_origin || true
  - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"

.git_tag: &git_tag
  - version=$(npx pnpm json -f package.json version)
  - git tag "$version"
  - git push --tags ssh_origin

stages:
  - install
  - build
  - test
  - version

version-2:
  stage: version
  variables:
    BRANCH_NAME: 'prod'
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $BRANCH_NAME
      when: on_success
  before_script:
    - *git_config
    - *prepare-pnpm
  script:
    - pnpm install json --save-dev --store=node_modules/.pnpm-store
    - pnpm json -I -f package.json -e "const versionPart = this.version.split('.');this.version=versionPart[0] + '.' + versionPart[1] + '.' + (Number(versionPart[2]) + 1)"
    - git add package.json
    - git commit -m "update version [ci skip]"
    - git push ssh_origin HEAD:$CI_COMMIT_REF_NAME
  after_script:
    - *git_tag

install:
  stage: install
  script:
    - *prepare-pnpm
    - pnpm i

test-build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  dependencies:
    - install
  script:
    - *prepare-pnpm
    - pnpm j b

test-vitest:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  dependencies:
    - install
  script:
    - *prepare-pnpm
    - pnpm j c
    - pnpm j t

test-playwright:
  stage: test
  image: mcr.microsoft.com/playwright:v1.31.0-focal
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  dependencies:
    - install
  script:
    - *prepare-pnpm
    - pnpm j c
    - npx playwright install
    - pnpm j test-browser

test-ts:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - install
  script:
    - *prepare-pnpm
    - pnpm j c
    - pnpm j eslint --fix ./src
