[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && VITE_CONTEXT=$CONTEXT VITE_COMMIT_REF=$COMMIT_REF npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''