export { default as Table } from './table'
export { default as THead } from './thead'
export { default as Td } from './td'
export { default as TdDataLabel } from './tdDataLabel'
export { default as Tr } from './tr'
