classDiagram
class MenuProp {
  <<interface>>
  name: string
  icon: any
  component: any
  needsReport?: boolean
  openedOnMobile?: boolean
}



class GenericContainerProps {
  <<interface>>
  element?: any
  xxxl?: boolean
  xxl?: boolean
  xl?: boolean
  lg?: boolean
  sm?: boolean
  full?: boolean
  horizontal?: boolean
  vertical?: boolean
  rounded?: boolean
  colorless?: boolean
  transparent?: boolean
  primary?: boolean
  secondary?: boolean
  tertiary?: boolean
  black?: boolean
  red?: boolean
  orange?: boolean
  amber?: boolean
  yellow?: boolean
  lime?: boolean
  green?: boolean
  emerald?: boolean
  teal?: boolean
  cyan?: boolean
  sky?: boolean
  blue?: boolean
  indigo?: boolean
  violet?: boolean
  purple?: boolean
  fuchsia?: boolean
  pink?: boolean
  rose?: boolean
  clickable?: boolean
  focusable?: boolean
  disabled?: boolean
  svg?: any
  leftSvg?: any
  rightSvg?: any
  src?: string
  leftSrc?: string
  rightSrc?: string
  containerClasses?: string
  illustrationClasses?: string
  leftIllustrationClasses?: string
  rightIllustrationClasses?: string
}



class GenericIllustrationProps {
  <<interface>>
  right?: boolean
}

GenericContainerProps <|-- GenericIllustrationProps

class MathNumberObject {
  <<interface>>
  [key: string]: MathNumber | MathNumber[] | MathNumber[][]
}
MathNumberObject <.. MathNumber


class ComputedData {
  <<interface>>
  raw: MathNumberObject
  parameters: MathNumberObject
  computed: MathNumberObject
  compute: #40;#41; =#62; void
}
ComputedData <.. MathNumberObject


class DataLabel {
  <<interface>>
  name: string
  unit: MathUnit
}
DataLabel <.. MathUnit


class DataValue {
  <<interface>>
  label: DataLabel
  value: MathNumber | MathNumber[] | MathNumber[][]
}
DataValue <.. DataLabel
DataValue <.. MathNumber


class BaseDrop {
  <<interface>>
  data: ComputedData
  additionnalFields: MachineField[]
}
BaseDrop <.. ComputedData


class JSONDrop {
  <<interface>>

}



class BaseField {
  <<interface>>
  label: string
  value: | boolean     | number     | string     | SlidableNumber     | DateValue     | LongString     | SelectableString
}
BaseField <.. SlidableNumber
BaseField <.. DateValue
BaseField <.. LongString
BaseField <.. SelectableString


class JSONField {
  <<interface>>
  label: string
  value: boolean | number | string
}



class SlidableNumber {
  <<interface>>
  kind: 'slidableNumber'
  value: number
  step: number
  min: number
  max: number
}



class DateValue {
  <<interface>>
  kind: 'date'
  value: string
}



class LongString {
  <<interface>>
  kind: 'longString'
  value: string
}



class SelectableString {
  <<interface>>
  kind: 'selectableString'
  value: string
  possibleValues: string[]
  strict: boolean
}



class HeavydynField {
  <<interface>>

}

BaseField <|-- HeavydynField

class MaxidynField {
  <<interface>>

}

BaseField <|-- MaxidynField

class MinidynField {
  <<interface>>

}

BaseField <|-- MinidynField

class Icon {
  <<interface>>
  element: HTMLElement
  color: string
  setText: #40;text: string#41; =#62; void
  setIcon: #40;iconName: IconName#41; =#62; void
}



class Image {
  <<interface>>
  id: string
  sourceData: mapboxgl.ImageSourceRaw
  markerNW: mapboxgl.Marker
  markerSE: mapboxgl.Marker
  opacity: number
  addToMap: #40;isVisible: boolean#41; =#62; void
  remove: #40;#41; =#62; void
}



class JSONImage {
  <<interface>>
  name: string
  opacity?: number
  coordinates?: #123;     nw: LngLat     se: LngLat   #125;
}
JSONImage <.. LngLat


class ImageCoordinates {
  <<interface>>
  tl: XYCoord
  tr: XYCoord
  bl: XYCoord
  br: XYCoord
}
ImageCoordinates <.. XYCoord


class Line {
  <<interface>>
  addToMap: #40;#41; =#62; void
  update: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}



class MathNumber {
  <<interface>>
  value: math.Unit | number
  unit: MathUnit | string
  displayString: string
  displayStringWithUnit: string
  toDisplayedValue: #40;#41; =#62; void
}
MathNumber <.. MathUnit


class MathUnit {
  <<interface>>
  name: string
  currentUnit: string
  currentPrecision: number
  possibleSettings: [string, number][]
  possiblePrecisions: number[]
  minDisplayedValue?: number
  maxDisplayedValue?: number
  thresholds?: #123;     selected: PredefinedThreshold | CustomThreshold | null     list: PredefinedThreshold[]     // custom: CustomThreshold   #125;
}
MathUnit <.. PredefinedThreshold
MathUnit <.. CustomThreshold


class BasePoint {
  <<interface>>
  machine: MachineName
  number: number
  marker: mapboxgl.Marker
  icon: Icon
  settings: JSONPointSettings
  zone: Zone | null
  data: DataValue[]
  updateText: #40;#41; =#62; void
  updateVisibility: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BasePoint <.. Icon
BasePoint <.. JSONPointSettings
BasePoint <.. Zone
BasePoint <.. DataValue


class BasePointCreatorParameters {
  <<interface>>
  machine: MachineName
}

MachinePointCreatorParameters <|-- BasePointCreatorParameters

class JSONPoint {
  <<interface>>
  coordinates: mapboxgl.LngLatLike
  settings: JSONPointSettings
  informations: JSONField[]
  drops: JSONDrop[]
}
JSONPoint <.. JSONPointSettings
JSONPoint <.. JSONField
JSONPoint <.. JSONDrop


class JSONPointSettings {
  <<interface>>
  isVisible: boolean
}



class HeavydynPoint {
  <<interface>>
  machine: 'heavydyn'
}

BasePoint <|-- HeavydynPoint

class MaxidynPoint {
  <<interface>>
  machine: 'maxidyn'
}

BasePoint <|-- MaxidynPoint

class MinidynPoint {
  <<interface>>
  machine: 'minidyn'
}

BasePoint <|-- MinidynPoint

class MachinePointCreatorParameters {
  <<interface>>
  number: number
  iconName: IconName
  projectSettings: JSONProjectSettings
  reportSettings: JSONReportSettings
}
MachinePointCreatorParameters <.. JSONProjectSettings
MachinePointCreatorParameters <.. JSONReportSettings


class BaseProject {
  <<interface>>
  machine: MachineName
  name: MachineField
  informations: MachineField[]
  reports: SelectableList#60;MachineReport#62;
  units: MachineUnits
  settings: JSONProjectSettings
  images: Image[]
  refreshLinesAndImages: #40;#41; =#62; void
  setMapStyle: #40;styleIndex: number#41; =#62; void
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseProject <.. JSONProjectSettings
BaseProject <.. Image


class BaseProjectCreatorParameters {
  <<interface>>
  machine: MachineName
  units: MachineUnits
}



class JSONProject {
  <<interface>>
  name: string
  machine: MachineName
  selectedReport?: number
  settings: JSONProjectSettings
  images: JSONImage[]
  informations: JSONField[]
  reports: JSONReport[]
  units: JSONUnits
}
JSONProject <.. JSONProjectSettings
JSONProject <.. JSONImage
JSONProject <.. JSONField
JSONProject <.. JSONReport


class JSONProjectSettings {
  <<interface>>
  arePointsVisible: boolean
  arePointsLinked: boolean
  arePointsLocked: boolean
  areImagesVisible: boolean
  pointsState: PointsState
  map: #123;     styleIndex: number     coordinates?: LngLat     zoom?: number   #125;
}
JSONProjectSettings <.. LngLat


class HeavydynProject {
  <<interface>>
  machine: 'heavydyn'
  reports: SelectableList#60;HeavydynReport#62;
}
HeavydynProject <.. HeavydynReport
BaseProject <|-- HeavydynProject

class HeavydynUnits {
  <<interface>>
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}
HeavydynUnits <.. MathUnit


class JSONHeavydynUnits {
  <<interface>>
  deformation: 'mm' | '1/100 mm' | 'um'
  force: 'N' | 'kN' | 'lbs'
  temperature: 'degC' | 'degF' | 'K'
}



class MaxidynProject {
  <<interface>>
  machine: 'maxidyn'
  reports: SelectableList#60;MaxidynReport#62;
}
MaxidynProject <.. MaxidynReport
BaseProject <|-- MaxidynProject

class MaxidynUnits {
  <<interface>>
  modulus: MathUnit
  deformation: MathUnit
  force: MathUnit
}
MaxidynUnits <.. MathUnit


class JSONMaxidynUnits {
  <<interface>>
  modulus: 'MPa' | 'kN'
  deformation: 'mm' | 'um'
  force: 'N' | 'kN'
}



class MinidynProject {
  <<interface>>
  machine: 'minidyn'
  reports: SelectableList#60;MinidynReport#62;
}
MinidynProject <.. MinidynReport
BaseProject <|-- MinidynProject

class MinidynUnits {
  <<interface>>
  modulus: MathUnit
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}
MinidynUnits <.. MathUnit


class JSONMinidynUnits {
  <<interface>>
  modulus: 'MPa' | 'kN'
  deformation: 'mm' | 'um'
  force: 'N' | 'kN'
}



class BaseReport {
  <<interface>>
  machine: MachineName
  name: MachineField
  points: MachinePoint[]
  line: Line
  zones: Zone[]
  screenshots: string[]
  dataLabels: ReportDataLabels
  settings: JSONReportSettings
  platform: MachineField[]
  informations: MachineField[]
  isOnMap: boolean
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseReport <.. Line
BaseReport <.. Zone
BaseReport <.. ReportDataLabels
BaseReport <.. JSONReportSettings


class ReportDataLabels {
  <<interface>>
  groups: SelectableList#60;GroupedDataLabels#62;
  table: SelectableList#60;TableDataLabelsParameters#62;
}
ReportDataLabels <.. GroupedDataLabels
ReportDataLabels <.. TableDataLabelsParameters


class GroupedDataLabels {
  <<interface>>
  from: DataLabelsFrom
  choices: SelectableList#60;DataLabel#62;
  indexes?: SelectableList#60;MachineDropIndex#62;
}
GroupedDataLabels <.. DataLabel


class TableDataLabelsParameters {
  <<interface>>
  group: GroupedDataLabels
  index?: MachineDropIndex
  dataLabels: DataLabel[]
}
TableDataLabelsParameters <.. GroupedDataLabels
TableDataLabelsParameters <.. DataLabel


class BaseReportCreatorParameters {
  <<interface>>
  machine: MachineName
  groupedDataLabels: SelectableList#60;GroupedDataLabels#62;
}
BaseReportCreatorParameters <.. GroupedDataLabels
MachineReportCreatorParameters <|-- BaseReportCreatorParameters

class JSONReport {
  <<interface>>
  name: string
  points: JSONPoint[]
  dataLabels: JSONReportDataLabels
  zones: JSONZone[]
  settings: JSONReportSettings
  screenshots: number[]
  platform: JSONField[]
  informations: JSONField[]
}
JSONReport <.. JSONPoint
JSONReport <.. JSONReportDataLabels
JSONReport <.. JSONZone
JSONReport <.. JSONReportSettings
JSONReport <.. JSONField


class JSONReportDataLabels {
  <<interface>>
  groups: SelectableList#60;number, JSONGroupedDataLabels#62;
  table: SelectableList#60;number, JSONTableDataLabelsParameters#62;
}
JSONReportDataLabels <.. JSONGroupedDataLabels
JSONReportDataLabels <.. JSONTableDataLabelsParameters


class JSONGroupedDataLabels {
  <<interface>>
  from: DataLabelsFrom
  choices: SelectableOptionalList#60;number, string#62;
  indexes?: SelectableList#60;number, MachineDropIndex#62;
}



class JSONTableDataLabelsParameters {
  <<interface>>
  from: DataLabelsFrom
  index?: number
  dataLabels: string[]
}



class JSONReportSettings {
  <<interface>>
  iconName: IconName
  isVisible: boolean
  selectedColorization: 'Threshold' | 'Zone'
  threshold: #123;     colors: ThresholdColors     custom: #123;#125;   #125;
}
JSONReportSettings <.. ThresholdColors


class ThresholdColors {
  <<interface>>
  low: Color
  middle: Color
  high: Color
}



class BaseDropIndex {
  <<interface>>
  machine: MachineName
  type: string
  displayedIndex: number
}



class HeavydynReport {
  <<interface>>
  machine: 'heavydyn'
  points: HeavydynPoint[]
  platform: HeavydynField[]
  informations: HeavydynField[]
}
HeavydynReport <.. HeavydynPoint
HeavydynReport <.. HeavydynField
BaseReport <|-- HeavydynReport

class HeavydynReportCreatorParameters {
  <<interface>>
  units: HeavydynUnits
}
HeavydynReportCreatorParameters <.. HeavydynUnits
MachineReportCreatorParameters <|-- HeavydynReportCreatorParameters

class HeavydynDropIndex {
  <<interface>>
  machine: 'heavydyn'
  type: HeavydynDropType
  value: MathNumber
}
HeavydynDropIndex <.. MathNumber
BaseDropIndex <|-- HeavydynDropIndex

class JSONHeavydynDropIndex {
  <<interface>>
  machine: 'heavydyn'
  type: HeavydynDropType
  value: number
}

BaseDropIndex <|-- JSONHeavydynDropIndex

class MaxidynReport {
  <<interface>>
  machine: 'maxidyn'
  points: MaxidynPoint[]
  platform: MaxidynField[]
  informations: MaxidynField[]
}
MaxidynReport <.. MaxidynPoint
MaxidynReport <.. MaxidynField
BaseReport <|-- MaxidynReport

class MaxidynReportCreatorParameters {
  <<interface>>
  units: MaxidynUnits
}
MaxidynReportCreatorParameters <.. MaxidynUnits
MachineReportCreatorParameters <|-- MaxidynReportCreatorParameters

class MaxidynDropIndex {
  <<interface>>
  machine: 'maxidyn'
  type: MaxidynDropType
}

BaseDropIndex <|-- MaxidynDropIndex

class MinidynReport {
  <<interface>>
  machine: 'minidyn'
  points: MinidynPoint[]
  platform: MinidynField[]
  informations: MinidynField[]
}
MinidynReport <.. MinidynPoint
MinidynReport <.. MinidynField
BaseReport <|-- MinidynReport

class MinidynReportCreatorParameters {
  <<interface>>
  units: MinidynUnits
}
MinidynReportCreatorParameters <.. MinidynUnits
MachineReportCreatorParameters <|-- MinidynReportCreatorParameters

class MinidynDropIndex {
  <<interface>>
  machine: 'minidyn'
  type: MinidynDropType
}

BaseDropIndex <|-- MinidynDropIndex

class MachineReportCreatorParameters {
  <<interface>>
  projectSettings: JSONProjectSettings
  units: MachineUnits
}
MachineReportCreatorParameters <.. JSONProjectSettings


class CustomThreshold {
  <<interface>>
  name: string
  value: number
}



class PredefinedThreshold {
  <<interface>>
  name: string
  value: number
}



class WatcherHandler {
  <<interface>>
  add: #40;stop: #40;#41; =#62; void#41; =#62; void
  remove: #40;stop: #40;#41; =#62; void#41; =#62; void
  clean: #40;#41; =#62; void
}



class Zone {
  <<interface>>
  name: string
  color: Color
}



class JSONZone {
  <<interface>>
  name: string
  color?: Color
}



class LngLat {
  <<interface>>
  lng: number
  lat: number
}



class XYCoord {
  <<interface>>
  x: number
  y: number
}



class SelectableList~S, L~ {
  <<interface>>
  selected: S | null
  list: L[]
}



class SelectableOptionalList~S, L~ {
  <<interface>>
  selected: S | null
  list?: L[]
}



class Store {
  <<interface>>
  projects: SelectableList#60;MachineProject#62;
  map: mapboxgl.Map | null
  save: #40;key: StoreKeys, value: StoreSaveableTypes#41; =#62; void
}



