classDiagram
class JSONMinidynDataLabelsGroup {
  <<type>>
  JSONMinidynDataLabelsGroups[number]
}
JSONMinidynDataLabelsGroup <.. JSONMinidynDataLabelsGroups


class JSONMinidynDataLabelsGroups {
  <<type>>
  [   JSONMinidynDropDataLabelsGroup,   JSONMinidynTestDataLabelsGroup,   JSONMinidynZoneDataLabelsGroup ]
}
JSONMinidynDataLabelsGroups <.. JSONMinidynDropDataLabelsGroup
JSONMinidynDataLabelsGroups <.. JSONMinidynTestDataLabelsGroup
JSONMinidynDataLabelsGroups <.. JSONMinidynZoneDataLabelsGroup


class AnyJSONMinidynDropDataLabelsGroup {
  <<type>>
  JSONMinidynDropDataLabelsGroup
}
AnyJSONMinidynDropDataLabelsGroup <.. JSONMinidynDropDataLabelsGroup


class JSONMinidynDropDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Drop', MinidynUnitsNames#62;
  distinct: JSONMinidynDropDataLabelsGroupDistinct
}
JSONMinidynDropDataLabelsGroup <.. MinidynUnitsNames
JSONMinidynDropDataLabelsGroup <.. JSONMinidynDropDataLabelsGroupDistinct


class JSONMinidynDropDataLabelsGroupDistinct {
  <<interface>>
  version: 1
  indexes: JSONSelectableList#60;JSONMinidynDropIndex#62;
}
JSONMinidynDropDataLabelsGroupDistinct <.. JSONMinidynDropIndex


class JSONMinidynTestDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Test', MinidynUnitsNames#62;
  distinct: JSONMinidynTestDataLabelsGroupDistinct
}
JSONMinidynTestDataLabelsGroup <.. MinidynUnitsNames
JSONMinidynTestDataLabelsGroup <.. JSONMinidynTestDataLabelsGroupDistinct


class JSONMinidynTestDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class JSONMinidynZoneDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Zone', MinidynUnitsNames#62;
  distinct: JSONMinidynZoneDataLabelsGroupDistinct
}
JSONMinidynZoneDataLabelsGroup <.. MinidynUnitsNames
JSONMinidynZoneDataLabelsGroup <.. JSONMinidynZoneDataLabelsGroupDistinct


class JSONMinidynZoneDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class MinidynDataLabels {
  <<interface>>
  groups: SelectableList#60;     MinidynDataLabelsGroup,     MinidynDataLabelsGroups   #62;
}
MinidynDataLabels <.. MinidynDataLabelsGroup
MinidynDataLabels <.. MinidynDataLabelsGroups


class MinidynDataLabelsGroup {
  <<type>>
  MinidynDataLabelsGroups[number]
}
MinidynDataLabelsGroup <.. MinidynDataLabelsGroups


class MinidynDataLabelsGroups {
  <<type>>
  [   MinidynDropDataLabelsGroup,   MinidynTestDataLabelsGroup,   MinidynZoneDataLabelsGroup ]
}
MinidynDataLabelsGroups <.. MinidynDropDataLabelsGroup
MinidynDataLabelsGroups <.. MinidynTestDataLabelsGroup
MinidynDataLabelsGroups <.. MinidynZoneDataLabelsGroup


class MinidynDropDataLabelsGroup {
  <<interface>>
  indexes: SelectableList#60;MinidynDropIndex#62;
  toJSON: #40;#41; =#62; JSONMinidynDropDataLabelsGroup
}
MinidynDropDataLabelsGroup <.. MinidynDropIndex


class MinidynTestDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMinidynTestDataLabelsGroup
}



class MinidynZoneDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMinidynZoneDataLabelsGroup
}



class JSONMinidynDropVAny {
  <<type>>
  JSONMinidynDrop
}
JSONMinidynDropVAny <.. JSONMinidynDrop


class JSONMinidynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONMinidynDropDistinct
}
JSONMinidynDrop <.. JSONMinidynDropDistinct


class JSONMinidynDropDistinct {
  <<interface>>
  version: 1
}



class JSONMinidynDropIndexVAny {
  <<type>>
  JSONMinidynDropIndex
}
JSONMinidynDropIndexVAny <.. JSONMinidynDropIndex


class JSONMinidynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONMinidynDropIndexDistinct
}
JSONMinidynDropIndex <.. JSONMinidynDropIndexDistinct


class JSONMinidynDropIndexDistinct {
  <<interface>>
  version: 1
  type: MinidynDropType
}
JSONMinidynDropIndexDistinct <.. MinidynDropType


class MinidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MinidynDrop {
  <<interface>>

}



class MinidynDropIndex {
  <<interface>>
  type: MinidynDropType
}
MinidynDropIndex <.. MinidynDropType


class MinidynUnitsSkeleton~A, B, C, D, E, F~ {
  <<interface>>
  modulus: A
  stiffness: B
  deflection: C
  force: D
  time: E
  percentage: F
}



class PossibleMinidynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleMinidynStiffnessUnits {
  <<type>>
  'MN / m'
}



class PossibleMinidynDeflectionUnits {
  <<type>>
  'mm' | 'um'
}



class PossibleMinidynForceUnits {
  <<type>>
  'N' | 'kN'
}



class PossibleMinidynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleMinidynPercentageUnits {
  <<type>>
  '%'
}



class JSONMinidynUnits {
  <<type>>
  MinidynUnitsSkeleton#60;   JSONMathUnit#60;PossibleMinidynModulusUnits#62;,   JSONMathUnit#60;PossibleMinidynStiffnessUnits#62;,   JSONMathUnit#60;PossibleMinidynDeflectionUnits#62;,   JSONMathUnit#60;PossibleMinidynForceUnits#62;,   JSONMathUnit#60;PossibleMinidynTimeUnits#62;,   JSONMathUnit#60;PossibleMinidynPercentageUnits#62; #62;
}
JSONMinidynUnits <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
JSONMinidynUnits <.. PossibleMinidynModulusUnits
JSONMinidynUnits <.. PossibleMinidynStiffnessUnits
JSONMinidynUnits <.. PossibleMinidynDeflectionUnits
JSONMinidynUnits <.. PossibleMinidynForceUnits
JSONMinidynUnits <.. PossibleMinidynTimeUnits
JSONMinidynUnits <.. PossibleMinidynPercentageUnits


class MinidynMathUnits {
  <<type>>
  MinidynUnitsSkeleton#60;   MathUnit#60;PossibleMinidynModulusUnits#62;,   MathUnit#60;PossibleMinidynStiffnessUnits#62;,   MathUnit#60;PossibleMinidynDeflectionUnits#62;,   MathUnit#60;PossibleMinidynForceUnits#62;,   MathUnit#60;PossibleMinidynTimeUnits#62;,   MathUnit#60;PossibleMinidynPercentageUnits#62; #62;
}
MinidynMathUnits <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
MinidynMathUnits <.. PossibleMinidynModulusUnits
MinidynMathUnits <.. PossibleMinidynStiffnessUnits
MinidynMathUnits <.. PossibleMinidynDeflectionUnits
MinidynMathUnits <.. PossibleMinidynForceUnits
MinidynMathUnits <.. PossibleMinidynTimeUnits
MinidynMathUnits <.. PossibleMinidynPercentageUnits


class MinidynUnitsNames {
  <<type>>
  keyof MinidynUnitsSkeleton#60;any#62;
}
MinidynUnitsNames <.. MinidynUnitsSkeleton~A, B, C, D, E, F~


class JSONMinidynPointVAny {
  <<type>>
  JSONMinidynPoint
}
JSONMinidynPointVAny <.. JSONMinidynPoint


class JSONMinidynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONMinidynPointDistinct
}
JSONMinidynPoint <.. JSONMinidynPointDistinct


class JSONMinidynPointDistinct {
  <<interface>>
  version: 1
}



class MinidynPoint {
  <<interface>>

}



class JSONMinidynProjectVAny {
  <<type>>
  JSONMinidynProject
}
JSONMinidynProjectVAny <.. JSONMinidynProject


class JSONMinidynProject {
  <<interface>>
  version: 1
  machine: 'Minidyn'
  base: JSONBaseProject
  distinct: JSONMinidynProjectDistinct
}
JSONMinidynProject <.. JSONMinidynProjectDistinct


class JSONMinidynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONMinidynUnits
  bearingParameters: JSONBearingParameters
}
JSONMinidynProjectDistinct <.. JSONMinidynUnits


class MinidynProject {
  <<interface>>
  bearingParameters: JSONBearingParameters
}



class JSONMinidynReportVAny {
  <<type>>
  JSONMinidynReport
}
JSONMinidynReportVAny <.. JSONMinidynReport


class JSONMinidynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONMinidynReportDistinct
}
JSONMinidynReport <.. JSONMinidynReportDistinct


class JSONMinidynReportDistinct {
  <<interface>>
  version: 1
  dataLabels: JSONSelectableList#60;     JSONMinidynDataLabelsGroup,     JSONMinidynDataLabelsGroups   #62;
  thresholds: JSONMinidynThresholdsConfigurations
}
JSONMinidynReportDistinct <.. JSONMinidynDataLabelsGroup
JSONMinidynReportDistinct <.. JSONMinidynDataLabelsGroups
JSONMinidynReportDistinct <.. JSONMinidynThresholdsConfigurations


class JSONMinidynThresholdsConfigurations {
  <<type>>
  MinidynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONMinidynThresholdsConfigurations <.. MinidynUnitsSkeleton~A, B, C, D, E, F~


class MinidynReport {
  <<interface>>
  addZone: #40;#41; =#62; void
}



class MinidynThresholds {
  <<interface>>

}



class MinidynThresholdsGroups {
  <<type>>
  MinidynUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}
MinidynThresholdsGroups <.. MinidynUnitsSkeleton~A, B, C, D, E, F~


class MinidynObject~T~ {
  <<interface>>

}



class MinidynZoneCreatorParameters {
  <<interface>>
  report: MinidynReport
}
MinidynZoneCreatorParameters <.. MinidynReport


class JSONMinidynZoneVAny {
  <<type>>
  JSONMinidynZone
}
JSONMinidynZoneVAny <.. JSONMinidynZone


class JSONMinidynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONMinidynZoneDistinct
}
JSONMinidynZone <.. JSONMinidynZoneDistinct


class JSONMinidynZoneDistinct {
  <<interface>>
  version: 1
}



class MinidynZone {
  <<interface>>

}



class MinidynExporter {
  <<interface>>
  export: #40;project: MinidynProject#41; =#62; Promise#60;File#62;
}



