classDiagram
class HeavydynField {
  <<interface>>

}



class MaxidynField {
  <<interface>>

}



class MinidynField {
  <<interface>>

}



class MachineField {
  <<type>>
  HeavydynField | MaxidynField | MinidynField
}
MachineField <.. HeavydynField
MachineField <.. MaxidynField
MachineField <.. MinidynField


class HeavydynPoint {
  <<interface>>
  machine: 'Heavydyn'
}



class MaxidynPoint {
  <<interface>>
  machine: 'Maxidyn'
}



class MinidynPoint {
  <<interface>>
  machine: 'Minidyn'
}



class MachinePoint {
  <<type>>
  HeavydynPoint | MaxidynPoint | MinidynPoint
}
MachinePoint <.. HeavydynPoint
MachinePoint <.. MaxidynPoint
MachinePoint <.. MinidynPoint


class PartialMachinePoint~MachinePoint~ {
  <<type>>
  PartialExtendedObject#60;   BasePoint,   MachinePoint #62;
}
PartialMachinePoint~MachinePoint~ <.. MachinePoint


class MachinePointCreatorParameters {
  <<interface>>
  number: number
  iconName: IconName
  projectSettings: JSONProjectSettings
  reportSettings: JSONReportSettings
}



class MachineName {
  <<type>>
  'Heavydyn' | 'Maxidyn' | 'Minidyn'
}



class HeavydynProject {
  <<interface>>
  machine: 'Heavydyn'
  reports: SelectableList#60;HeavydynReport#62;
}
HeavydynProject <.. HeavydynReport


class HeavydynUnits {
  <<interface>>
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}



class JSONHeavydynUnits {
  <<interface>>
  deformation: 'mm' | '1/100 mm' | 'um'
  force: 'N' | 'kN' | 'lbs'
  temperature: 'degC' | 'degF' | 'K'
}



class MaxidynProject {
  <<interface>>
  machine: 'Maxidyn'
  reports: SelectableList#60;MaxidynReport#62;
}
MaxidynProject <.. MaxidynReport


class MaxidynUnits {
  <<interface>>
  modulus: MathUnit
  deformation: MathUnit
  force: MathUnit
}



class JSONMaxidynUnits {
  <<interface>>
  modulus: 'MPa' | 'kN'
  deformation: 'mm' | 'um'
  force: 'N' | 'kN'
}



class MinidynProject {
  <<interface>>
  machine: 'Minidyn'
  reports: SelectableList#60;MinidynReport#62;
}
MinidynProject <.. MinidynReport


class MinidynUnits {
  <<interface>>
  modulus: MathUnit
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}



class JSONMinidynUnits {
  <<interface>>
  modulus: 'MPa' | 'kN'
  deformation: 'mm' | 'um'
  force: 'N' | 'kN'
}



class MachineProject {
  <<type>>
  HeavydynProject | MaxidynProject | MinidynProject
}
MachineProject <.. HeavydynProject
MachineProject <.. MaxidynProject
MachineProject <.. MinidynProject


class PartialMachineProject~MachineProject~ {
  <<type>>
  PartialExtendedObject#60;   BaseProject,   MachineProject #62;
}
PartialMachineProject~MachineProject~ <.. MachineProject


class MachineUnits {
  <<type>>
  HeavydynUnits | MaxidynUnits | MinidynUnits
}
MachineUnits <.. HeavydynUnits
MachineUnits <.. MaxidynUnits
MachineUnits <.. MinidynUnits


class HeavydynReport {
  <<interface>>
  machine: 'Heavydyn'
  points: HeavydynPoint[]
  platform: HeavydynField[]
  informations: HeavydynField[]
}
HeavydynReport <.. HeavydynPoint
HeavydynReport <.. HeavydynField


class HeavydynReportCreatorParameters {
  <<interface>>
  units: HeavydynUnits
}
HeavydynReportCreatorParameters <.. HeavydynUnits
MachineReportCreatorParameters <|-- HeavydynReportCreatorParameters

class HeavydynDropType {
  <<type>>
  'Distance' | 'Force' | 'Time'
}



class HeavydynDropIndex {
  <<interface>>
  machine: 'Heavydyn'
  type: HeavydynDropType
  value: MathNumber
}
HeavydynDropIndex <.. HeavydynDropType


class JSONHeavydynDropIndex {
  <<interface>>
  machine: 'Heavydyn'
  type: HeavydynDropType
  value: number
}
JSONHeavydynDropIndex <.. HeavydynDropType


class MaxidynReport {
  <<interface>>
  machine: 'Maxidyn'
  points: MaxidynPoint[]
  platform: MaxidynField[]
  informations: MaxidynField[]
}
MaxidynReport <.. MaxidynPoint
MaxidynReport <.. MaxidynField


class MaxidynReportCreatorParameters {
  <<interface>>
  units: MaxidynUnits
}
MaxidynReportCreatorParameters <.. MaxidynUnits
MachineReportCreatorParameters <|-- MaxidynReportCreatorParameters

class MaxidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MaxidynDropIndex {
  <<interface>>
  machine: 'Maxidyn'
  type: MaxidynDropType
}
MaxidynDropIndex <.. MaxidynDropType


class MinidynReport {
  <<interface>>
  machine: 'Minidyn'
  points: MinidynPoint[]
  platform: MinidynField[]
  informations: MinidynField[]
}
MinidynReport <.. MinidynPoint
MinidynReport <.. MinidynField


class MinidynReportCreatorParameters {
  <<interface>>
  units: MinidynUnits
}
MinidynReportCreatorParameters <.. MinidynUnits
MachineReportCreatorParameters <|-- MinidynReportCreatorParameters

class MinidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MinidynDropIndex {
  <<interface>>
  machine: 'Minidyn'
  type: MinidynDropType
}
MinidynDropIndex <.. MinidynDropType


class MachineReport {
  <<type>>
  HeavydynReport | MaxidynReport | MinidynReport
}
MachineReport <.. HeavydynReport
MachineReport <.. MaxidynReport
MachineReport <.. MinidynReport


class PartialMachineReport~MachineReport~ {
  <<type>>
  PartialExtendedObject#60;   BaseReport,   MachineReport #62;
}
PartialMachineReport~MachineReport~ <.. MachineReport


class MachineReportCreatorParameters {
  <<interface>>
  projectSettings: JSONProjectSettings
  units: MachineUnits
}
MachineReportCreatorParameters <.. MachineUnits


class MachineDropIndex {
  <<type>>
  HeavydynDropIndex | MaxidynDropIndex | MinidynDropIndex
}
MachineDropIndex <.. HeavydynDropIndex
MachineDropIndex <.. MaxidynDropIndex
MachineDropIndex <.. MinidynDropIndex


class JSONMachineDropIndex {
  <<type>>
  | JSONHeavydynDropIndex   | MaxidynDropIndex   | MinidynDropIndex
}
JSONMachineDropIndex <.. JSONHeavydynDropIndex
JSONMachineDropIndex <.. MaxidynDropIndex
JSONMachineDropIndex <.. MinidynDropIndex


class PartialExtendedObject~BaseObject, MachineObject~ {
  <<type>>
  Required#60;BaseObject#62; &   Partial#60;Omit#60;MachineObject, keyof BaseObject#62;#62;
}



