classDiagram
class HeavydynField {
  <<interface>>

}



class HeavydynPoint {
  <<interface>>
  machine: 'Heavydyn'
}



class HeavydynProject {
  <<interface>>
  machine: 'Heavydyn'
  reports: SelectableList#60;HeavydynReport#62;
}
HeavydynProject <.. HeavydynReport


class HeavydynUnits {
  <<interface>>
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}



class JSONHeavydynUnits {
  <<interface>>
  deformation: 'mm' | '1/100 mm' | 'um'
  force: 'N' | 'kN' | 'lbs'
  temperature: 'degC' | 'degF' | 'K'
}



class HeavydynReport {
  <<interface>>
  machine: 'Heavydyn'
  points: HeavydynPoint[]
  platform: HeavydynField[]
  informations: HeavydynField[]
}
HeavydynReport <.. HeavydynPoint
HeavydynReport <.. HeavydynField


class HeavydynReportCreatorParameters {
  <<interface>>
  units: HeavydynUnits
}
HeavydynReportCreatorParameters <.. HeavydynUnits


class HeavydynDropType {
  <<type>>
  'Distance' | 'Force' | 'Time'
}



class HeavydynDropIndex {
  <<interface>>
  machine: 'Heavydyn'
  type: HeavydynDropType
  value: MathNumber
}
HeavydynDropIndex <.. HeavydynDropType


class JSONHeavydynDropIndex {
  <<interface>>
  machine: 'Heavydyn'
  type: HeavydynDropType
  value: number
}
JSONHeavydynDropIndex <.. HeavydynDropType


