classDiagram
class Menu {
  <<interface>>
  name: string
  icon: any
  component: any
  props: MenuProps
  needsReport?: boolean
  style?: string
  class?: string
  openedOnMobile?: boolean
}
Menu <.. MenuProps


class MenuProps {
  <<interface>>
  route: string
}



class GenericContainerProps {
  <<interface>>
  element?: any
  xxxl?: boolean
  xxl?: boolean
  xl?: boolean
  lg?: boolean
  sm?: boolean
  full?: boolean
  horizontal?: boolean
  vertical?: boolean
  rounded?: boolean
  colorless?: boolean
  transparent?: boolean
  primary?: boolean
  secondary?: boolean
  tertiary?: boolean
  black?: boolean
  red?: boolean
  orange?: boolean
  amber?: boolean
  yellow?: boolean
  lime?: boolean
  green?: boolean
  emerald?: boolean
  teal?: boolean
  cyan?: boolean
  sky?: boolean
  blue?: boolean
  indigo?: boolean
  violet?: boolean
  purple?: boolean
  fuchsia?: boolean
  pink?: boolean
  rose?: boolean
  clickable?: boolean
  focusable?: boolean
  disabled?: boolean
  svg?: any
  leftSvg?: any
  rightSvg?: any
  src?: string
  leftSrc?: string
  rightSrc?: string
  containerClasses?: string
  illustrationClasses?: string
  leftIllustrationClasses?: string
  rightIllustrationClasses?: string
}



class GenericIllustrationProps {
  <<interface>>
  right?: boolean
}

GenericContainerProps <|-- GenericIllustrationProps

class Color {
  <<interface>>
  buttonColors: string
  iconsClasses: string
  hexColor: string
}



class ColorName {
  <<type>>
  | 'gray'   | 'red'   | 'orange'   | 'amber'   | 'yellow'   | 'lime'   | 'green'   | 'emerald'   | 'teal'   | 'cyan'   | 'sky'   | 'blue'   | 'indigo'   | 'violet'   | 'purple'   | 'fuchsia'   | 'pink'   | 'rose'
}



class MathNumberObject {
  <<interface>>
  [key: string]: MathNumber | MathNumber[] | MathNumber[][]
}
MathNumberObject <.. MathNumber


class ComputedData {
  <<interface>>
  raw: MathNumberObject
  parameters: MathNumberObject
  computed: MathNumberObject
  compute: #40;#41; =#62; void
}
ComputedData <.. MathNumberObject


class JSONDataLabelVAny~T~ {
  <<type>>
  JSONDataLabel#60;T#62;
}
JSONDataLabelVAny~T~ <.. JSONDataLabel~T~


class JSONDataLabel~T~ {
  <<interface>>
  version: 1
  name: string
  unit: T
}



class DataLabel~T~ {
  <<interface>>
  name: string
  unit: MathUnit#60;T#62;
  scientificName?: string
}
DataLabel~T~ <.. MathUnit~PossibleUnits~


class JSONDataValueVAny {
  <<type>>
  JSONDataValue
}
JSONDataValueVAny <.. JSONDataValue


class JSONDataValue {
  <<interface>>
  version: 1
  label: string
  value: number
}



class DataValue~T~ {
  <<interface>>
  label: DataLabel#60;T#62;
  value: MathNumber
  toJSON: #40;#41; =#62; JSONDataValue
}
DataValue~T~ <.. DataLabel~T~
DataValue~T~ <.. MathNumber


class BaseDropCreatorParameters {
  <<interface>>
  machine: MachineName
}
BaseDropCreatorParameters <.. MachineName
MachineDropCreatorParameters <|-- BaseDropCreatorParameters

class JSONBaseDropVAny {
  <<type>>
  JSONBaseDrop
}
JSONBaseDropVAny <.. JSONBaseDrop


class JSONBaseDrop {
  <<interface>>
  version: 1
  index: number
  data: JSONDataValue[]
}
JSONBaseDrop <.. JSONDataValue


class JSONBaseDropIndexVAny {
  <<type>>
  JSONBaseDropIndex
}
JSONBaseDropIndexVAny <.. JSONBaseDropIndex


class JSONBaseDropIndex {
  <<interface>>
  version: 1
  displayedIndex: number
}



class BaseDrop {
  <<interface>>
  index: MachineDropIndex
  data: DataValue#60;string#62;[]
  point: MachinePoint
  impactData: ImpactData | null
  toBaseJSON: #40;#41; =#62; JSONBaseDrop
}
BaseDrop <.. MachineDropIndex
BaseDrop <.. DataValue~T~
BaseDrop <.. MachinePoint
BaseDrop <.. ImpactData


class BaseDropIndex {
  <<interface>>
  displayedIndex: number
  toBaseJSON: #40;#41; =#62; JSONBaseDropIndex
}



class HeavydynDropCreatorParameters {
  <<interface>>
  point: HeavydynPoint
}
HeavydynDropCreatorParameters <.. HeavydynPoint
MachineDropCreatorParameters <|-- HeavydynDropCreatorParameters

class JSONHeavydynDropVAny {
  <<type>>
  JSONHeavydynDrop
}
JSONHeavydynDropVAny <.. JSONHeavydynDrop


class JSONHeavydynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONHeavydynDropDistinct
}
JSONHeavydynDrop <.. JSONBaseDrop
JSONHeavydynDrop <.. JSONHeavydynDropDistinct


class JSONHeavydynDropDistinct {
  <<interface>>
  version: 1
}



class JSONHeavydynDropIndexVAny {
  <<type>>
  JSONHeavydynDropIndex
}
JSONHeavydynDropIndexVAny <.. JSONHeavydynDropIndex


class JSONHeavydynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONHeavydynDropIndexDistinct
}
JSONHeavydynDropIndex <.. JSONBaseDropIndex
JSONHeavydynDropIndex <.. JSONHeavydynDropIndexDistinct


class JSONHeavydynDropIndexDistinct {
  <<interface>>
  version: 1
  type: HeavydynDropType
  value: number
  unit: string
}
JSONHeavydynDropIndexDistinct <.. HeavydynDropType


class HeavydynDropType {
  <<type>>
  'Distance' | 'Time' | 'Force' | 'Height'
}



class HeavydynDrop {
  <<interface>>
  index: HeavydynDropIndex
  point: HeavydynPoint
  toJSON: #40;#41; =#62; JSONHeavydynDrop
}
HeavydynDrop <.. HeavydynDropIndex
HeavydynDrop <..< HeavydynPoint
BaseDrop <|-- HeavydynDrop

class HeavydynDropIndex {
  <<interface>>
  machine: 'Heavydyn'
  type: HeavydynDropType
  value: MathNumber
  toJSON: #40;#41; =#62; JSONHeavydynDropIndex
}
HeavydynDropIndex <.. HeavydynDropType
HeavydynDropIndex <.. MathNumber
BaseDropIndex <|-- HeavydynDropIndex

class MaxidynDropCreatorParameters {
  <<interface>>
  point: MaxidynPoint
}
MaxidynDropCreatorParameters <.. MaxidynPoint
MachineDropCreatorParameters <|-- MaxidynDropCreatorParameters

class JSONMaxidynDropVAny {
  <<type>>
  JSONMaxidynDrop
}
JSONMaxidynDropVAny <.. JSONMaxidynDrop


class JSONMaxidynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONMaxidynDropDistinct
}
JSONMaxidynDrop <.. JSONBaseDrop
JSONMaxidynDrop <.. JSONMaxidynDropDistinct


class JSONMaxidynDropDistinct {
  <<interface>>
  version: 1
}



class JSONMaxidynDropIndexVAny {
  <<type>>
  JSONMaxidynDropIndex
}
JSONMaxidynDropIndexVAny <.. JSONMaxidynDropIndex


class JSONMaxidynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONMaxidynDropIndexDistinct
}
JSONMaxidynDropIndex <.. JSONBaseDropIndex
JSONMaxidynDropIndex <.. JSONMaxidynDropIndexDistinct


class JSONMaxidynDropIndexDistinct {
  <<interface>>
  version: 1
  type: MaxidynDropType
}
JSONMaxidynDropIndexDistinct <.. MaxidynDropType


class MaxidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MaxidynDrop {
  <<interface>>
  index: MaxidynDropIndex
  point: MaxidynPoint
  toJSON: #40;#41; =#62; JSONMaxidynDrop
}
MaxidynDrop <.. MaxidynDropIndex
MaxidynDrop <..< MaxidynPoint
BaseDrop <|-- MaxidynDrop

class MaxidynDropIndex {
  <<interface>>
  machine: 'Maxidyn'
  type: MaxidynDropType
  toJSON: #40;#41; =#62; JSONMaxidynDropIndex
}
MaxidynDropIndex <.. MaxidynDropType
BaseDropIndex <|-- MaxidynDropIndex

class MinidynDropCreatorParameters {
  <<interface>>
  point: MinidynPoint
}
MinidynDropCreatorParameters <.. MinidynPoint
MachineDropCreatorParameters <|-- MinidynDropCreatorParameters

class JSONMinidynDropVAny {
  <<type>>
  JSONMinidynDrop
}
JSONMinidynDropVAny <.. JSONMinidynDrop


class JSONMinidynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONMinidynDropDistinct
}
JSONMinidynDrop <.. JSONBaseDrop
JSONMinidynDrop <.. JSONMinidynDropDistinct


class JSONMinidynDropDistinct {
  <<interface>>
  version: 1
}



class JSONMinidynDropIndexVAny {
  <<type>>
  JSONMinidynDropIndex
}
JSONMinidynDropIndexVAny <.. JSONMinidynDropIndex


class JSONMinidynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONMinidynDropIndexDistinct
}
JSONMinidynDropIndex <.. JSONBaseDropIndex
JSONMinidynDropIndex <.. JSONMinidynDropIndexDistinct


class JSONMinidynDropIndexDistinct {
  <<interface>>
  version: 1
  type: MinidynDropType
}
JSONMinidynDropIndexDistinct <.. MinidynDropType


class MinidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MinidynDrop {
  <<interface>>
  index: MinidynDropIndex
  point: MinidynPoint
  toJSON: #40;#41; =#62; JSONMinidynDrop
}
MinidynDrop <.. MinidynDropIndex
MinidynDrop <..< MinidynPoint
BaseDrop <|-- MinidynDrop

class MinidynDropIndex {
  <<interface>>
  machine: 'Minidyn'
  type: MinidynDropType
  toJSON: #40;#41; =#62; JSONMinidynDropIndex
}
MinidynDropIndex <.. MinidynDropType
BaseDropIndex <|-- MinidynDropIndex

class JSONMachineDropIndex {
  <<type>>
  | JSONHeavydynDropIndex   | JSONMaxidynDropIndex   | JSONMinidynDropIndex
}
JSONMachineDropIndex <.. JSONHeavydynDropIndex
JSONMachineDropIndex <.. JSONMaxidynDropIndex
JSONMachineDropIndex <.. JSONMinidynDropIndex


class JSONMachineDrop {
  <<type>>
  JSONHeavydynDrop | JSONMaxidynDrop | JSONMinidynDrop
}
JSONMachineDrop <.. JSONHeavydynDrop
JSONMachineDrop <.. JSONMaxidynDrop
JSONMachineDrop <.. JSONMinidynDrop


class MachineDrop {
  <<type>>
  HeavydynDrop | MaxidynDrop | MinidynDrop
}
MachineDrop <.. HeavydynDrop
MachineDrop <.. MaxidynDrop
MachineDrop <.. MinidynDrop


class PartialMachineDrop~MachineDrop~ {
  <<type>>
  PartialExtendedObject#60;   BaseDrop,   MachineDrop #62;
}
PartialMachineDrop~MachineDrop~ <.. PartialExtendedObject~BaseObject, MachineObject~
PartialMachineDrop~MachineDrop~ <.. BaseDrop
PartialMachineDrop~MachineDrop~ <.. MachineDrop


class MachineDropCreatorParameters {
  <<interface>>
  point: MachinePoint
}
MachineDropCreatorParameters <.. MachinePoint


class JSONFieldVAny {
  <<type>>
  JSONField
}
JSONFieldVAny <.. JSONField


class JSONField {
  <<interface>>
  version: 1
  label: string
  value: boolean | number | string
  settings: JSONFieldSettings
}
JSONField <.. JSONFieldSettings


class JSONFieldSettings {
  <<interface>>
  version: 1
  readOnly?: true
}



class Field {
  <<interface>>
  label: string
  settings: JSONFieldSettings
  value: | boolean     | number     | string     | SlidableNumber     | DateValue     | LongString     | SelectableString
  getValue: #40;#41; =#62; string | number | boolean
  setValue: #40;value: string | number#41; =#62; void
  toString: #40;#41; =#62; string
  toJSON: #40;#41; =#62; JSONField
}
Field <.. JSONFieldSettings
Field <.. SlidableNumber
Field <.. DateValue
Field <.. LongString
Field <.. SelectableString


class SlidableNumber {
  <<interface>>
  kind: 'slidableNumber'
  step: number
  min: number
  max: number
  value: number
}



class DateValue {
  <<interface>>
  kind: 'dateValue'
  value: string
}



class LongString {
  <<interface>>
  kind: 'longString'
  value: string
}



class SelectableString {
  <<interface>>
  kind: 'selectableString'
  possibleValues: string[]
  value: string
}



class Icon {
  <<interface>>
  element: HTMLElement
  color: string
  setColor: #40;color?: string#41; =#62; void
  setText: #40;text: string#41; =#62; void
  setIcon: #40;iconName: IconName#41; =#62; void
}



class IconName {
  <<type>>
  | 'Circle'   | 'Triangle'   | 'Square'   | 'Rhombus'   | 'Flare'   | 'Pentagon'   | 'Hexagon'   | 'HexagonAlt'   | 'Heptagon'   | 'Octagon'
}



class Line {
  <<interface>>
  sortedPoints: MachinePoint[]
  addToMap: #40;#41; =#62; void
  update: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
Line <.. MachinePoint


class MathNumber {
  <<interface>>
  value: number
  unit: MathUnit#60;string#62;
  displayedString: string
  displayedStringWithUnit: string
  updateDisplayedStrings: #40;#41; =#62; void
  getLocaleString: #40;     options: MathNumberGetLocaleStringOptions   #41; =#62; string
  getValueAs: #40;unit: string#41; =#62; number
}
MathNumber <.. MathUnit~PossibleUnits~


class MathNumberGetLocaleStringOptions {
  <<interface>>
  appendUnitToString?: true
  locale?: string
  precision?: number
  disablePreString?: true
  unit?: string
  removeSpaces?: true
  disableMinAndMax?: true
}



class HeavydynUnitsSkeleton~A, B, C, D, E~ {
  <<interface>>
  deflection: A
  force: B
  temperature: C
  distance: D
  time: E
}



class HeavydynUnitsNames {
  <<type>>
  keyof HeavydynUnitsSkeleton#60;any#62;
}
HeavydynUnitsNames <.. HeavydynUnitsSkeleton~A, B, C, D, E~


class PossibleHeavydynDeflectionUnits {
  <<type>>
  'mm' | '1/100 mm' | 'um'
}



class PossibleHeavydynForceUnits {
  <<type>>
  'N' | 'kN' | 'lbs'
}



class PossibleHeavydynTemperatureUnits {
  <<type>>
  '°C' | '°F' | 'K'
}



class PossibleHeavydynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleHeavydynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class JSONHeavydynUnits {
  <<type>>
  HeavydynUnitsSkeleton#60;   JSONMathUnit#60;PossibleHeavydynDeflectionUnits#62;,   JSONMathUnit#60;PossibleHeavydynForceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTemperatureUnits#62;,   JSONMathUnit#60;PossibleHeavydynDistanceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTimeUnits#62; #62;
}
JSONHeavydynUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E~
JSONHeavydynUnits <.. JSONMathUnit~PossibleUnits~
JSONHeavydynUnits <.. PossibleHeavydynDeflectionUnits
JSONHeavydynUnits <.. PossibleHeavydynForceUnits
JSONHeavydynUnits <.. PossibleHeavydynTemperatureUnits
JSONHeavydynUnits <.. PossibleHeavydynDistanceUnits
JSONHeavydynUnits <.. PossibleHeavydynTimeUnits


class HeavydynMathUnits {
  <<type>>
  HeavydynUnitsSkeleton#60;   MathUnit#60;PossibleHeavydynDeflectionUnits#62;,   MathUnit#60;PossibleHeavydynForceUnits#62;,   MathUnit#60;PossibleHeavydynTemperatureUnits#62;,   MathUnit#60;PossibleHeavydynDistanceUnits#62;,   MathUnit#60;PossibleHeavydynTimeUnits#62; #62;
}
HeavydynMathUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E~
HeavydynMathUnits <.. MathUnit~PossibleUnits~
HeavydynMathUnits <.. PossibleHeavydynDeflectionUnits
HeavydynMathUnits <.. PossibleHeavydynForceUnits
HeavydynMathUnits <.. PossibleHeavydynTemperatureUnits
HeavydynMathUnits <.. PossibleHeavydynDistanceUnits
HeavydynMathUnits <.. PossibleHeavydynTimeUnits


class MaxidynUnitsSkeleton~A, B, C, D, E, F, G~ {
  <<interface>>
  modulus: A
  stiffness: B
  deflection: C
  force: D
  distance: E
  time: F
  percentage: G
}



class PossibleMaxidynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleMaxidynStiffnessUnits {
  <<type>>
  'MN / m'
}



class PossibleMaxidynDeflectionUnits {
  <<type>>
  'mm' | 'um'
}



class PossibleMaxidynForceUnits {
  <<type>>
  'N' | 'kN'
}



class PossibleMaxidynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleMaxidynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleMaxidynPercentageUnits {
  <<type>>
  '%'
}



class JSONMaxidynUnits {
  <<type>>
  MaxidynUnitsSkeleton#60;   JSONMathUnit#60;PossibleMaxidynModulusUnits#62;,   JSONMathUnit#60;PossibleMaxidynStiffnessUnits#62;,   JSONMathUnit#60;PossibleMaxidynDeflectionUnits#62;,   JSONMathUnit#60;PossibleMaxidynForceUnits#62;,   JSONMathUnit#60;PossibleMaxidynDistanceUnits#62;,   JSONMathUnit#60;PossibleMaxidynTimeUnits#62;,   JSONMathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
JSONMaxidynUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
JSONMaxidynUnits <.. JSONMathUnit~PossibleUnits~
JSONMaxidynUnits <.. PossibleMaxidynModulusUnits
JSONMaxidynUnits <.. PossibleMaxidynStiffnessUnits
JSONMaxidynUnits <.. PossibleMaxidynDeflectionUnits
JSONMaxidynUnits <.. PossibleMaxidynForceUnits
JSONMaxidynUnits <.. PossibleMaxidynDistanceUnits
JSONMaxidynUnits <.. PossibleMaxidynTimeUnits
JSONMaxidynUnits <.. PossibleMaxidynPercentageUnits


class MaxidynMathUnits {
  <<type>>
  MaxidynUnitsSkeleton#60;   MathUnit#60;PossibleMaxidynModulusUnits#62;,   MathUnit#60;PossibleMaxidynStiffnessUnits#62;,   MathUnit#60;PossibleMaxidynDeflectionUnits#62;,   MathUnit#60;PossibleMaxidynForceUnits#62;,   MathUnit#60;PossibleMaxidynDistanceUnits#62;,   MathUnit#60;PossibleMaxidynTimeUnits#62;,   MathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
MaxidynMathUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MaxidynMathUnits <.. MathUnit~PossibleUnits~
MaxidynMathUnits <.. PossibleMaxidynModulusUnits
MaxidynMathUnits <.. PossibleMaxidynStiffnessUnits
MaxidynMathUnits <.. PossibleMaxidynDeflectionUnits
MaxidynMathUnits <.. PossibleMaxidynForceUnits
MaxidynMathUnits <.. PossibleMaxidynDistanceUnits
MaxidynMathUnits <.. PossibleMaxidynTimeUnits
MaxidynMathUnits <.. PossibleMaxidynPercentageUnits


class MaxidynUnitsNames {
  <<type>>
  keyof MaxidynUnitsSkeleton#60;any#62;
}
MaxidynUnitsNames <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class MinidynUnitsSkeleton~A, B, C, D, E, F~ {
  <<interface>>
  modulus: A
  stiffness: B
  deflection: C
  force: D
  time: E
  percentage: F
}



class PossibleMinidynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleMinidynStiffnessUnits {
  <<type>>
  'MN / m'
}



class PossibleMinidynDeflectionUnits {
  <<type>>
  'mm' | 'um'
}



class PossibleMinidynForceUnits {
  <<type>>
  'N' | 'kN'
}



class PossibleMinidynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleMinidynPercentageUnits {
  <<type>>
  '%'
}



class JSONMinidynUnits {
  <<type>>
  MinidynUnitsSkeleton#60;   JSONMathUnit#60;PossibleMinidynModulusUnits#62;,   JSONMathUnit#60;PossibleMinidynStiffnessUnits#62;,   JSONMathUnit#60;PossibleMinidynDeflectionUnits#62;,   JSONMathUnit#60;PossibleMinidynForceUnits#62;,   JSONMathUnit#60;PossibleMinidynTimeUnits#62;,   JSONMathUnit#60;PossibleMinidynPercentageUnits#62; #62;
}
JSONMinidynUnits <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
JSONMinidynUnits <.. JSONMathUnit~PossibleUnits~
JSONMinidynUnits <.. PossibleMinidynModulusUnits
JSONMinidynUnits <.. PossibleMinidynStiffnessUnits
JSONMinidynUnits <.. PossibleMinidynDeflectionUnits
JSONMinidynUnits <.. PossibleMinidynForceUnits
JSONMinidynUnits <.. PossibleMinidynTimeUnits
JSONMinidynUnits <.. PossibleMinidynPercentageUnits


class MinidynMathUnits {
  <<type>>
  MinidynUnitsSkeleton#60;   MathUnit#60;PossibleMinidynModulusUnits#62;,   MathUnit#60;PossibleMinidynStiffnessUnits#62;,   MathUnit#60;PossibleMinidynDeflectionUnits#62;,   MathUnit#60;PossibleMinidynForceUnits#62;,   MathUnit#60;PossibleMinidynTimeUnits#62;,   MathUnit#60;PossibleMinidynPercentageUnits#62; #62;
}
MinidynMathUnits <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
MinidynMathUnits <.. MathUnit~PossibleUnits~
MinidynMathUnits <.. PossibleMinidynModulusUnits
MinidynMathUnits <.. PossibleMinidynStiffnessUnits
MinidynMathUnits <.. PossibleMinidynDeflectionUnits
MinidynMathUnits <.. PossibleMinidynForceUnits
MinidynMathUnits <.. PossibleMinidynTimeUnits
MinidynMathUnits <.. PossibleMinidynPercentageUnits


class MinidynUnitsNames {
  <<type>>
  keyof MinidynUnitsSkeleton#60;any#62;
}
MinidynUnitsNames <.. MinidynUnitsSkeleton~A, B, C, D, E, F~


class JSONMathUnit~PossibleUnits~ {
  <<interface>>
  version: 1
  currentUnit: PossibleUnits
  currentPrecision: number
  max: number
  min?: number
}



class MathUnit~PossibleUnits~ {
  <<interface>>
  name: string
  baseUnit: string
  possibleSettings: [PossibleUnits, number][]
  possiblePrecisions: number[]
  readOnly: boolean
  min: number
  max: number
  currentUnit: PossibleUnits
  currentPrecision: number
  getAverage: #40;values: number[]#41; =#62; number
  toJSON: #40;#41; =#62; JSONMathUnit#60;PossibleUnits#62;
}



class JSONOverlay {
  <<interface>>
  version: 1
  name: string
  opacity?: number
  coordinates?: #123;     nw: LngLat     se: LngLat   #125;
}
JSONOverlay <.. LngLat


class Overlay {
  <<interface>>
  id: string
  sourceData: mapboxgl.ImageSourceRaw
  markerNW: mapboxgl.Marker
  markerSE: mapboxgl.Marker
  opacity: number
  addToMap: #40;isVisible: boolean#41; =#62; void
  remove: #40;#41; =#62; void
  toJSON: #40;#41; =#62; JSONOverlay
}



class ImageCoordinates {
  <<interface>>
  tl: XYCoord
  tr: XYCoord
  bl: XYCoord
  br: XYCoord
}
ImageCoordinates <.. XYCoord


class BasePointCreatorParameters {
  <<interface>>
  machine: MachineName
}
BasePointCreatorParameters <.. MachineName
MachinePointCreatorParameters <|-- BasePointCreatorParameters

class JSONBasePointVAny {
  <<type>>
  JSONBasePoint
}
JSONBasePointVAny <.. JSONBasePoint


class JSONBasePoint {
  <<interface>>
  version: 1
  id: string
  number: number
  index: number
  date: string
  coordinates: mapboxgl.LngLatLike
  data: JSONDataValue[]
  settings: JSONPointSettings
  information: JSONField[]
  drops: JSONMachineDrop[]
}
JSONBasePoint <.. JSONDataValue
JSONBasePoint <.. JSONPointSettings
JSONBasePoint <.. JSONField
JSONBasePoint <.. JSONMachineDrop


class JSONPointSettings {
  <<interface>>
  version: 1
  isVisible: boolean
}



class BasePoint {
  <<interface>>
  machine: MachineName
  id: string
  date: Date
  marker: mapboxgl.Marker | null
  icon: Icon | null
  settings: JSONPointSettings
  data: DataValue#60;string#62;[]
  information: Field[]
  drops: MachineDrop[]
  index: number
  number: number
  zone: MachineZone
  rawDataFile: ArrayBufferLike | null
  getSelectedMathNumber: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: MachineDropIndex | null   #41; =#62; MathNumber | undefined
  getDisplayedString: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: MachineDropIndex | null   #41; =#62; string
  updateColor: #40;#41; =#62; void
  updateText: #40;#41; =#62; void
  updateVisibility: #40;#41; =#62; void
  updatePopup: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  checkVisibility: #40;#41; =#62; boolean
  remove: #40;#41; =#62; void
  toBaseJSON: #40;#41; =#62; JSONBasePoint
}
BasePoint <.. MachineName
BasePoint <.. Icon
BasePoint <.. JSONPointSettings
BasePoint <.. DataValue~T~
BasePoint <.. Field
BasePoint <.. MachineDrop
BasePoint <.. MachineZone


class HeavydynPointCreatorParameters {
  <<interface>>
  zone: HeavydynZone
}
HeavydynPointCreatorParameters <.. HeavydynZone
MachinePointCreatorParameters <|-- HeavydynPointCreatorParameters

class JSONHeavydynPointVAny {
  <<type>>
  JSONHeavydynPoint
}
JSONHeavydynPointVAny <.. JSONHeavydynPoint


class JSONHeavydynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONHeavydynPointDistinct
}
JSONHeavydynPoint <.. JSONBasePoint
JSONHeavydynPoint <.. JSONHeavydynPointDistinct


class JSONHeavydynPointDistinct {
  <<interface>>
  version: 1
}



class HeavydynPoint {
  <<interface>>
  machine: 'Heavydyn'
  drops: HeavydynDrop[]
  zone: HeavydynZone
  toJSON: #40;#41; =#62; JSONHeavydynPoint
}
HeavydynPoint <..< HeavydynZone
BasePoint <|-- HeavydynPoint

class MaxidynPointCreatorParameters {
  <<interface>>
  zone: MaxidynZone
}
MaxidynPointCreatorParameters <.. MaxidynZone
MachinePointCreatorParameters <|-- MaxidynPointCreatorParameters

class JSONMaxidynPointVAny {
  <<type>>
  JSONMaxidynPoint
}
JSONMaxidynPointVAny <.. JSONMaxidynPoint


class JSONMaxidynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONMaxidynPointDistinct
}
JSONMaxidynPoint <.. JSONBasePoint
JSONMaxidynPoint <.. JSONMaxidynPointDistinct


class JSONMaxidynPointDistinct {
  <<interface>>
  version: 1
}



class MaxidynPoint {
  <<interface>>
  machine: 'Maxidyn'
  drops: MaxidynDrop[]
  zone: MaxidynZone
  toJSON: #40;#41; =#62; JSONMaxidynPoint
}
MaxidynPoint <..< MaxidynZone
BasePoint <|-- MaxidynPoint

class MinidynPointCreatorParameters {
  <<interface>>
  zone: MinidynZone
}
MinidynPointCreatorParameters <.. MinidynZone
MachinePointCreatorParameters <|-- MinidynPointCreatorParameters

class JSONMinidynPointVAny {
  <<type>>
  JSONMinidynPoint
}
JSONMinidynPointVAny <.. JSONMinidynPoint


class JSONMinidynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONMinidynPointDistinct
}
JSONMinidynPoint <.. JSONBasePoint
JSONMinidynPoint <.. JSONMinidynPointDistinct


class JSONMinidynPointDistinct {
  <<interface>>
  version: 1
}



class MinidynPoint {
  <<interface>>
  machine: 'Minidyn'
  drops: MinidynDrop[]
  zone: MinidynZone
  toJSON: #40;#41; =#62; JSONMinidynPoint
}
MinidynPoint <..< MinidynZone
BasePoint <|-- MinidynPoint

class JSONMachinePoint {
  <<type>>
  JSONHeavydynPoint | JSONMaxidynPoint | JSONMinidynPoint
}
JSONMachinePoint <.. JSONHeavydynPoint
JSONMachinePoint <.. JSONMaxidynPoint
JSONMachinePoint <.. JSONMinidynPoint


class MachinePoint {
  <<type>>
  HeavydynPoint | MaxidynPoint | MinidynPoint
}
MachinePoint <.. HeavydynPoint
MachinePoint <.. MaxidynPoint
MachinePoint <.. MinidynPoint


class PartialMachinePoint~MachinePoint~ {
  <<type>>
  PartialExtendedObject#60;   BasePoint,   MachinePoint #62;
}
PartialMachinePoint~MachinePoint~ <.. PartialExtendedObject~BaseObject, MachineObject~
PartialMachinePoint~MachinePoint~ <.. BasePoint
PartialMachinePoint~MachinePoint~ <.. MachinePoint


class MachinePointCreatorParameters {
  <<interface>>
  zone: MachineZone
}
MachinePointCreatorParameters <.. MachineZone


class JSONBaseProjectVAny {
  <<type>>
  JSONBaseProject
}
JSONBaseProjectVAny <.. JSONBaseProject


class JSONBaseProject {
  <<interface>>
  version: 1
  name: string
  machine: MachineName
  reports: SelectableList#60;number, JSONMachineReport#62;
  settings: JSONProjectSettings
  overlays: JSONOverlay[]
  information: JSONField[]
  hardware: JSONField[]
  acquisitionParameters: JSONAcquisitionParameters
}
JSONBaseProject <.. MachineName
JSONBaseProject <.. SelectableList~S, L~
JSONBaseProject <.. JSONMachineReport
JSONBaseProject <.. JSONProjectSettings
JSONBaseProject <.. JSONOverlay
JSONBaseProject <.. JSONField
JSONBaseProject <.. JSONAcquisitionParameters


class MachineName {
  <<type>>
  'Heavydyn' | 'Maxidyn' | 'Minidyn'
}



class JSONProjectSettings {
  <<interface>>
  version: 1
  arePointsVisible: boolean
  arePointsLinked: boolean
  arePointsLocked: boolean
  areOverlaysVisible: boolean
  pointsState: 'value' | 'number' | 'nothing'
  map: #123;     version: 1     styleIndex: number     coordinates: LngLat | null     zoom: number | null   #125;
}
JSONProjectSettings <.. LngLat


class JSONAcquisitionParameters {
  <<interface>>
  version: 1
  nbSamples: number
  frequency: number
  preTrig: number
  smoothing?: boolean
}



class BaseProject {
  <<interface>>
  machine: MachineName
  name: Field
  information: Field[]
  hardware: Field[]
  reports: SelectableList#60;MachineReport#62;
  units: MachineMathUnits
  settings: JSONProjectSettings
  overlays: Overlay[]
  acquisitionParameters: JSONAcquisitionParameters
  refreshLinesAndOverlays: #40;#41; =#62; void
  setMapStyle: #40;styleIndex: number#41; =#62; void
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
  toBaseJSON: #40;#41; =#62; JSONBaseProject
}
BaseProject <.. MachineName
BaseProject <.. Field
BaseProject <.. SelectableList~S, L~
BaseProject <.. MachineReport
BaseProject <.. MachineMathUnits
BaseProject <.. JSONProjectSettings
BaseProject <.. Overlay
BaseProject <.. JSONAcquisitionParameters


class JSONHeavydynProjectVAny {
  <<type>>
  JSONHeavydynProject
}
JSONHeavydynProjectVAny <.. JSONHeavydynProject


class JSONHeavydynProject {
  <<interface>>
  version: 1
  base: JSONBaseProject
  distinct: JSONHeavydynProjectDistinct
}
JSONHeavydynProject <.. JSONBaseProject
JSONHeavydynProject <.. JSONHeavydynProjectDistinct


class JSONHeavydynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONHeavydynUnits
  calibrations: JSONHeavydynCalibrations
}
JSONHeavydynProjectDistinct <.. JSONHeavydynUnits
JSONHeavydynProjectDistinct <.. JSONHeavydynCalibrations


class JSONHeavydynCalibrations {
  <<interface>>
  version: 1
  date: string
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}
JSONHeavydynCalibrations <.. JSONChannel
JSONHeavydynCalibrations <.. JSONSensor


class JSONChannel {
  <<interface>>
  version: 1
  name: string
  position: string
  gain: number
  acquisition: number
  type: 'LoadCell' | 'Geophone'
}



class JSONSensor {
  <<interface>>
  version: 1
  name: string
  gain: number
  type: 'AirTemp' | 'SurfTemp' | 'Dmi'
}



class HeavydynProject {
  <<interface>>
  machine: 'Heavydyn'
  reports: SelectableList#60;HeavydynReport#62;
  units: HeavydynMathUnits
  calibrations: HeavydynCalibrations
  toJSON: #40;#41; =#62; JSONHeavydynProject
}
HeavydynProject <.. SelectableList~S, L~
HeavydynProject <..< HeavydynReport
HeavydynProject <.. HeavydynMathUnits
HeavydynProject <.. HeavydynCalibrations
BaseProject <|-- HeavydynProject

class HeavydynCalibrations {
  <<interface>>
  date: Date
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}
HeavydynCalibrations <.. JSONChannel
HeavydynCalibrations <.. JSONSensor


class JSONMaxidynProjectVAny {
  <<type>>
  JSONMaxidynProject
}
JSONMaxidynProjectVAny <.. JSONMaxidynProject


class JSONMaxidynProject {
  <<interface>>
  version: 1
  base: JSONBaseProject
  distinct: JSONMaxidynProjectDistinct
}
JSONMaxidynProject <.. JSONBaseProject
JSONMaxidynProject <.. JSONMaxidynProjectDistinct


class JSONMaxidynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONMaxidynUnits
  bearingParameters: JSONBearingParameters
}
JSONMaxidynProjectDistinct <.. JSONMaxidynUnits
JSONMaxidynProjectDistinct <.. JSONBearingParameters


class MaxidynProject {
  <<interface>>
  machine: 'Maxidyn'
  reports: SelectableList#60;MaxidynReport#62;
  units: MaxidynMathUnits
  bearingParameters: JSONBearingParameters
  toJSON: #40;#41; =#62; JSONMaxidynProject
}
MaxidynProject <.. SelectableList~S, L~
MaxidynProject <..< MaxidynReport
MaxidynProject <.. MaxidynMathUnits
MaxidynProject <.. JSONBearingParameters
BaseProject <|-- MaxidynProject

class JSONMinidynProjectVAny {
  <<type>>
  JSONMinidynProject
}
JSONMinidynProjectVAny <.. JSONMinidynProject


class JSONMinidynProject {
  <<interface>>
  version: 1
  base: JSONBaseProject
  distinct: JSONMinidynProjectDistinct
}
JSONMinidynProject <.. JSONBaseProject
JSONMinidynProject <.. JSONMinidynProjectDistinct


class JSONMinidynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONMinidynUnits
  bearingParameters: JSONBearingParameters
}
JSONMinidynProjectDistinct <.. JSONMinidynUnits
JSONMinidynProjectDistinct <.. JSONBearingParameters


class MinidynProject {
  <<interface>>
  machine: 'Minidyn'
  reports: SelectableList#60;MinidynReport#62;
  units: MinidynMathUnits
  bearingParameters: JSONBearingParameters
  toJSON: #40;#41; =#62; JSONMinidynProject
}
MinidynProject <.. SelectableList~S, L~
MinidynProject <..< MinidynReport
MinidynProject <.. MinidynMathUnits
MinidynProject <.. JSONBearingParameters
BaseProject <|-- MinidynProject

class JSONMachineProject {
  <<type>>
  | JSONHeavydynProject   | JSONMaxidynProject   | JSONMinidynProject
}
JSONMachineProject <.. JSONHeavydynProject
JSONMachineProject <.. JSONMaxidynProject
JSONMachineProject <.. JSONMinidynProject


class JSONBearingParameters {
  <<interface>>
  version: 1
  name: string
  algoBearing: string
  hasQuality: boolean
  algoProcessing1: string
  algoProcessing2: string
  dPlate: number
  cPoisson: number
  fForme: number
  k: number
  alpha: number
}



class MachineProject {
  <<type>>
  HeavydynProject | MaxidynProject | MinidynProject
}
MachineProject <.. HeavydynProject
MachineProject <.. MaxidynProject
MachineProject <.. MinidynProject


class PartialMachineProject~MachineProject~ {
  <<type>>
  PartialExtendedObject#60;   BaseProject,   MachineProject #62;
}
PartialMachineProject~MachineProject~ <.. PartialExtendedObject~BaseObject, MachineObject~
PartialMachineProject~MachineProject~ <.. BaseProject
PartialMachineProject~MachineProject~ <.. MachineProject


class MachineMathUnits {
  <<type>>
  HeavydynMathUnits | MaxidynMathUnits | MinidynMathUnits
}
MachineMathUnits <.. HeavydynMathUnits
MachineMathUnits <.. MaxidynMathUnits
MachineMathUnits <.. MinidynMathUnits


class MachineUnitsSkeleton~T~ {
  <<type>>
  | HeavydynUnitsSkeleton#60;T#62;   | MaxidynUnitsSkeleton#60;T#62;   | MinidynUnitsSkeleton#60;T#62;
}
MachineUnitsSkeleton~T~ <.. HeavydynUnitsSkeleton~A, B, C, D, E~
MachineUnitsSkeleton~T~ <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MachineUnitsSkeleton~T~ <.. MinidynUnitsSkeleton~A, B, C, D, E, F~


class MachineUnitsNames {
  <<type>>
  | HeavydynUnitsNames   | MaxidynUnitsNames   | MinidynUnitsNames
}
MachineUnitsNames <.. HeavydynUnitsNames
MachineUnitsNames <.. MaxidynUnitsNames
MachineUnitsNames <.. MinidynUnitsNames


class JSONBaseReportVAny {
  <<type>>
  JSONBaseReport
}
JSONBaseReportVAny <.. JSONBaseReport


class JSONBaseReport {
  <<interface>>
  version: 1
  name: string
  zones: JSONMachineZone[]
  settings: JSONReportSettings
  screenshots: number[]
  platform: JSONField[]
  information: JSONField[]
  dataLabels: JSONBaseReportDataLabels
  thresholds: JSONBaseReportThresholds
}
JSONBaseReport <.. JSONMachineZone
JSONBaseReport <.. JSONReportSettings
JSONBaseReport <.. JSONField
JSONBaseReport <.. JSONBaseReportDataLabels
JSONBaseReport <.. JSONBaseReportThresholds


class JSONBaseReportDataLabels {
  <<interface>>
  version: 1
  table: SelectableList#60;number, JSONTableDataLabelsParameters#62;
}
JSONBaseReportDataLabels <.. SelectableList~S, L~
JSONBaseReportDataLabels <.. JSONTableDataLabelsParameters


class JSONTableDataLabelsParameters {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  index?: number
  dataLabels: string[]
}
JSONTableDataLabelsParameters <.. DataLabelsFrom


class DataLabelsFrom {
  <<type>>
  'Drop' | 'Test' | 'Zone'
}



class JSONBaseReportThresholds {
  <<interface>>
  version: 1
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}
JSONBaseReportThresholds <.. JSONThresholdColors
JSONBaseReportThresholds <.. JSONThresholdInputs


class JSONThresholdColors {
  <<interface>>
  version: 1
  low: ColorName
  middle: ColorName
  high: ColorName
}
JSONThresholdColors <.. ColorName


class JSONThresholdInputs {
  <<interface>>
  version: 1
  isRequiredARange: boolean
  isOptionalARange: boolean
}



class JSONReportSettings {
  <<interface>>
  version: 1
  iconName: IconName
  isVisible: boolean
  colorization: ReportColorization
  groupBy: ReportGroupBy
}
JSONReportSettings <.. IconName
JSONReportSettings <.. ReportColorization
JSONReportSettings <.. ReportGroupBy


class ReportColorization {
  <<type>>
  'Threshold' | 'Zone'
}



class ReportGroupBy {
  <<type>>
  'Number' | 'Zone'
}



class BaseReport {
  <<interface>>
  machine: MachineName
  name: Field
  line: Line
  zones: MachineZone[]
  screenshots: string[]
  dataLabels: MachineReportDataLabels
  thresholds: MachineReportThresholds
  settings: JSONReportSettings
  platform: Field[]
  information: Field[]
  project: MachineProject
  isOnMap: boolean
  fitOnMap: #40;#41; =#62; void
  toBaseJSON: #40;#41; =#62; JSONBaseReport
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseReport <.. MachineName
BaseReport <.. Field
BaseReport <.. Line
BaseReport <.. MachineZone
BaseReport <.. MachineReportDataLabels
BaseReport <.. MachineReportThresholds
BaseReport <.. JSONReportSettings
BaseReport <.. MachineProject


class BaseReportDataLabels {
  <<interface>>
  groups: SelectableList#60;BaseGroupedDataLabels#62;
  table: SelectableList#60;BaseTableDataLabelsParameters#62;
}
BaseReportDataLabels <.. SelectableList~S, L~
BaseReportDataLabels <.. BaseGroupedDataLabels
BaseReportDataLabels <.. BaseTableDataLabelsParameters


class BaseGroupedDataLabels {
  <<interface>>
  from: DataLabelsFrom
  choices: SelectableList#60;DataLabel#60;string#62;#62;
  indexes?: SelectableList#60;MachineDropIndex#62;
}
BaseGroupedDataLabels <.. DataLabelsFrom
BaseGroupedDataLabels <.. SelectableList~S, L~
BaseGroupedDataLabels <.. DataLabel~T~
BaseGroupedDataLabels <.. MachineDropIndex


class BaseTableDataLabelsParameters {
  <<interface>>
  group: MachineGroupedDataLabels
  index?: MachineDropIndex
  dataLabels: DataLabel#60;string#62;[]
}
BaseTableDataLabelsParameters <.. MachineGroupedDataLabels
BaseTableDataLabelsParameters <.. MachineDropIndex
BaseTableDataLabelsParameters <.. DataLabel~T~


class BaseReportThresholds {
  <<interface>>
  groups: MachineUnitsSkeleton#60;GroupedThresolds#60;string#62;#62;
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}
BaseReportThresholds <.. MachineUnitsSkeleton~T~
BaseReportThresholds <.. GroupedThresolds~T~
BaseReportThresholds <.. JSONThresholdColors
BaseReportThresholds <.. JSONThresholdInputs


class GroupedThresolds~T~ {
  <<interface>>
  unit: MathUnit#60;T#62;
  choices: SelectableList#60;AnyThreshold#62;
}
GroupedThresolds~T~ <.. MathUnit~PossibleUnits~
GroupedThresolds~T~ <.. SelectableList~S, L~
GroupedThresolds~T~ <.. AnyThreshold


class HeavydynReportCreatorParameters {
  <<interface>>
  project: HeavydynProject
}
HeavydynReportCreatorParameters <.. HeavydynProject
MachineReportCreatorParameters <|-- HeavydynReportCreatorParameters

class JSONHeavydynReportVAny {
  <<type>>
  JSONHeavydynReport
}
JSONHeavydynReportVAny <.. JSONHeavydynReport


class JSONHeavydynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONHeavydynReportDistinct
}
JSONHeavydynReport <.. JSONBaseReport
JSONHeavydynReport <.. JSONHeavydynReportDistinct


class JSONHeavydynReportDistinct {
  <<interface>>
  version: 1
  groupedDataLabels: SelectableList#60;     number,     JSONHeavydynGroupedDataLabels   #62;
  thresholds: HeavydynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONHeavydynReportDistinct <.. SelectableList~S, L~
JSONHeavydynReportDistinct <.. JSONHeavydynGroupedDataLabels
JSONHeavydynReportDistinct <.. HeavydynUnitsSkeleton~A, B, C, D, E~
JSONHeavydynReportDistinct <.. JSONDistinctThresholdsConfiguration


class JSONHeavydynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;HeavydynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONHeavydynDropIndex#62;
}
JSONHeavydynGroupedDataLabels <.. DataLabelsFrom
JSONHeavydynGroupedDataLabels <.. SelectableList~S, L~
JSONHeavydynGroupedDataLabels <.. JSONDataLabel~T~
JSONHeavydynGroupedDataLabels <.. HeavydynUnitsNames
JSONHeavydynGroupedDataLabels <.. JSONHeavydynDropIndex


class HeavydynReport {
  <<interface>>
  machine: 'Heavydyn'
  zones: HeavydynZone[]
  dataLabels: HeavydynReportDataLabels
  thresholds: HeavydynReportThresholds
  project: HeavydynProject
  toJSON: #40;#41; =#62; JSONHeavydynReport
}
HeavydynReport <.. HeavydynZone
HeavydynReport <.. HeavydynReportDataLabels
HeavydynReport <.. HeavydynReportThresholds
BaseReport <|-- HeavydynReport

class HeavydynReportDataLabels {
  <<interface>>
  groups: SelectableList#60;HeavydynGroupedDataLabels#62;
  table: SelectableList#60;HeavydynTableDataLabelsParameters#62;
}
HeavydynReportDataLabels <.. SelectableList~S, L~
HeavydynReportDataLabels <.. HeavydynGroupedDataLabels
HeavydynReportDataLabels <.. HeavydynTableDataLabelsParameters
BaseReportDataLabels <|-- HeavydynReportDataLabels

class HeavydynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;HeavydynDropIndex#62;
  sequenceName?: string
}
HeavydynGroupedDataLabels <.. SelectableList~S, L~
HeavydynGroupedDataLabels <.. HeavydynDropIndex
BaseGroupedDataLabels <|-- HeavydynGroupedDataLabels

class HeavydynTableDataLabelsParameters {
  <<interface>>
  group: HeavydynGroupedDataLabels
  index?: HeavydynDropIndex
}
HeavydynTableDataLabelsParameters <.. HeavydynGroupedDataLabels
HeavydynTableDataLabelsParameters <.. HeavydynDropIndex
BaseTableDataLabelsParameters <|-- HeavydynTableDataLabelsParameters

class HeavydynReportThresholds {
  <<interface>>
  groups: HeavydynUnitsSkeleton#60;GroupedThresolds#60;string#62;#62;
}
HeavydynReportThresholds <.. HeavydynUnitsSkeleton~A, B, C, D, E~
HeavydynReportThresholds <.. GroupedThresolds~T~
BaseReportThresholds <|-- HeavydynReportThresholds

class HeavydynReportThresholdsGroups {
  <<type>>
  HeavydynUnitsSkeleton#60;   GroupedThresolds#60;string#62; #62;
}
HeavydynReportThresholdsGroups <.. HeavydynUnitsSkeleton~A, B, C, D, E~
HeavydynReportThresholdsGroups <.. GroupedThresolds~T~


class MaxidynReportCreatorParameters {
  <<interface>>
  project: MaxidynProject
}
MaxidynReportCreatorParameters <.. MaxidynProject
MachineReportCreatorParameters <|-- MaxidynReportCreatorParameters

class JSONMaxidynReportVAny {
  <<type>>
  JSONMaxidynReport
}
JSONMaxidynReportVAny <.. JSONMaxidynReport


class JSONMaxidynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONMaxidynReportDistinct
}
JSONMaxidynReport <.. JSONBaseReport
JSONMaxidynReport <.. JSONMaxidynReportDistinct


class JSONMaxidynReportDistinct {
  <<interface>>
  version: 1
  groupedDataLabels: SelectableList#60;     number,     JSONMaxidynGroupedDataLabels   #62;
  thresholds: MaxidynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONMaxidynReportDistinct <.. SelectableList~S, L~
JSONMaxidynReportDistinct <.. JSONMaxidynGroupedDataLabels
JSONMaxidynReportDistinct <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
JSONMaxidynReportDistinct <.. JSONDistinctThresholdsConfiguration


class JSONMaxidynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;MaxidynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONMaxidynDropIndex#62;
}
JSONMaxidynGroupedDataLabels <.. DataLabelsFrom
JSONMaxidynGroupedDataLabels <.. SelectableList~S, L~
JSONMaxidynGroupedDataLabels <.. JSONDataLabel~T~
JSONMaxidynGroupedDataLabels <.. MaxidynUnitsNames
JSONMaxidynGroupedDataLabels <.. JSONMaxidynDropIndex


class MaxidynReport {
  <<interface>>
  machine: 'Maxidyn'
  zones: MaxidynZone[]
  dataLabels: MaxidynReportDataLabels
  thresholds: MaxidynReportThresholds
  project: MaxidynProject
  toJSON: #40;#41; =#62; JSONMaxidynReport
}
MaxidynReport <.. MaxidynZone
MaxidynReport <.. MaxidynReportDataLabels
MaxidynReport <.. MaxidynReportThresholds
BaseReport <|-- MaxidynReport

class MaxidynReportDataLabels {
  <<interface>>
  groups: SelectableList#60;MaxidynGroupedDataLabels#62;
  table: SelectableList#60;MaxidynTableDataLabelsParameters#62;
}
MaxidynReportDataLabels <.. SelectableList~S, L~
MaxidynReportDataLabels <.. MaxidynGroupedDataLabels
MaxidynReportDataLabels <.. MaxidynTableDataLabelsParameters
BaseReportDataLabels <|-- MaxidynReportDataLabels

class MaxidynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;MaxidynDropIndex#62;
}
MaxidynGroupedDataLabels <.. SelectableList~S, L~
MaxidynGroupedDataLabels <.. MaxidynDropIndex
BaseGroupedDataLabels <|-- MaxidynGroupedDataLabels

class MaxidynTableDataLabelsParameters {
  <<interface>>
  group: MaxidynGroupedDataLabels
  index?: MaxidynDropIndex
}
MaxidynTableDataLabelsParameters <.. MaxidynGroupedDataLabels
MaxidynTableDataLabelsParameters <.. MaxidynDropIndex
BaseTableDataLabelsParameters <|-- MaxidynTableDataLabelsParameters

class MaxidynReportThresholds {
  <<interface>>
  groups: MaxidynUnitsSkeleton#60;GroupedThresolds#60;string#62;#62;
}
MaxidynReportThresholds <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MaxidynReportThresholds <.. GroupedThresolds~T~
BaseReportThresholds <|-- MaxidynReportThresholds

class MaxidynReportThresholdsGroups {
  <<type>>
  MaxidynUnitsSkeleton#60;   GroupedThresolds#60;string#62; #62;
}
MaxidynReportThresholdsGroups <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MaxidynReportThresholdsGroups <.. GroupedThresolds~T~


class MinidynReportCreatorParameters {
  <<interface>>
  project: MinidynProject
}
MinidynReportCreatorParameters <.. MinidynProject
MachineReportCreatorParameters <|-- MinidynReportCreatorParameters

class JSONMinidynReportVAny {
  <<type>>
  JSONMinidynReport
}
JSONMinidynReportVAny <.. JSONMinidynReport


class JSONMinidynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONMinidynReportDistinct
}
JSONMinidynReport <.. JSONBaseReport
JSONMinidynReport <.. JSONMinidynReportDistinct


class JSONMinidynReportDistinct {
  <<interface>>
  version: 1
  groupedDataLabels: SelectableList#60;     number,     JSONMinidynGroupedDataLabels   #62;
  thresholds: MinidynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONMinidynReportDistinct <.. SelectableList~S, L~
JSONMinidynReportDistinct <.. JSONMinidynGroupedDataLabels
JSONMinidynReportDistinct <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
JSONMinidynReportDistinct <.. JSONDistinctThresholdsConfiguration


class JSONMinidynGroupedDataLabels {
  <<interface>>
  version: 1
  from: DataLabelsFrom
  choices: SelectableList#60;number, JSONDataLabel#60;MinidynUnitsNames#62;#62;
  indexes?: SelectableList#60;number, JSONMinidynDropIndex#62;
}
JSONMinidynGroupedDataLabels <.. DataLabelsFrom
JSONMinidynGroupedDataLabels <.. SelectableList~S, L~
JSONMinidynGroupedDataLabels <.. JSONDataLabel~T~
JSONMinidynGroupedDataLabels <.. MinidynUnitsNames
JSONMinidynGroupedDataLabels <.. JSONMinidynDropIndex


class MinidynReport {
  <<interface>>
  machine: 'Minidyn'
  zones: MinidynZone[]
  dataLabels: MinidynReportDataLabels
  thresholds: MinidynReportThresholds
  project: MinidynProject
  toJSON: #40;#41; =#62; JSONMinidynReport
}
MinidynReport <.. MinidynZone
MinidynReport <.. MinidynReportDataLabels
MinidynReport <.. MinidynReportThresholds
BaseReport <|-- MinidynReport

class MinidynReportDataLabels {
  <<interface>>
  groups: SelectableList#60;MinidynGroupedDataLabels#62;
  table: SelectableList#60;MinidynTableDataLabelsParameters#62;
}
MinidynReportDataLabels <.. SelectableList~S, L~
MinidynReportDataLabels <.. MinidynGroupedDataLabels
MinidynReportDataLabels <.. MinidynTableDataLabelsParameters
BaseReportDataLabels <|-- MinidynReportDataLabels

class MinidynGroupedDataLabels {
  <<interface>>
  indexes?: SelectableList#60;MinidynDropIndex#62;
}
MinidynGroupedDataLabels <.. SelectableList~S, L~
MinidynGroupedDataLabels <.. MinidynDropIndex
BaseGroupedDataLabels <|-- MinidynGroupedDataLabels

class MinidynTableDataLabelsParameters {
  <<interface>>
  group: MinidynGroupedDataLabels
  index?: MinidynDropIndex
}
MinidynTableDataLabelsParameters <.. MinidynGroupedDataLabels
MinidynTableDataLabelsParameters <.. MinidynDropIndex
BaseTableDataLabelsParameters <|-- MinidynTableDataLabelsParameters

class MinidynReportThresholds {
  <<interface>>
  groups: MinidynReportThresholdsGroups
}
MinidynReportThresholds <.. MinidynReportThresholdsGroups
BaseReportThresholds <|-- MinidynReportThresholds

class MinidynReportThresholdsGroups {
  <<type>>
  MinidynUnitsSkeleton#60;   GroupedThresolds#60;string#62; #62;
}
MinidynReportThresholdsGroups <.. MinidynUnitsSkeleton~A, B, C, D, E, F~
MinidynReportThresholdsGroups <.. GroupedThresolds~T~


class JSONMachineReport {
  <<type>>
  | JSONHeavydynReport   | JSONMaxidynReport   | JSONMinidynReport
}
JSONMachineReport <.. JSONHeavydynReport
JSONMachineReport <.. JSONMaxidynReport
JSONMachineReport <.. JSONMinidynReport


class JSONMachineGroupedDataLabels {
  <<type>>
  | JSONHeavydynGroupedDataLabels   | JSONMaxidynGroupedDataLabels   | JSONMinidynGroupedDataLabels
}
JSONMachineGroupedDataLabels <.. JSONHeavydynGroupedDataLabels
JSONMachineGroupedDataLabels <.. JSONMaxidynGroupedDataLabels
JSONMachineGroupedDataLabels <.. JSONMinidynGroupedDataLabels


class PartialMachineReport~MachineReport~ {
  <<type>>
  PartialExtendedObject#60;   BaseReport,   MachineReport #62;
}
PartialMachineReport~MachineReport~ <.. PartialExtendedObject~BaseObject, MachineObject~
PartialMachineReport~MachineReport~ <.. BaseReport
PartialMachineReport~MachineReport~ <.. MachineReport


class MachineReport {
  <<type>>
  HeavydynReport | MaxidynReport | MinidynReport
}
MachineReport <.. HeavydynReport
MachineReport <.. MaxidynReport
MachineReport <.. MinidynReport


class MachineGroupedDataLabels {
  <<type>>
  | HeavydynGroupedDataLabels   | MaxidynGroupedDataLabels   | MinidynGroupedDataLabels
}
MachineGroupedDataLabels <.. HeavydynGroupedDataLabels
MachineGroupedDataLabels <.. MaxidynGroupedDataLabels
MachineGroupedDataLabels <.. MinidynGroupedDataLabels


class MachineDropIndex {
  <<type>>
  HeavydynDropIndex | MaxidynDropIndex | MinidynDropIndex
}
MachineDropIndex <.. HeavydynDropIndex
MachineDropIndex <.. MaxidynDropIndex
MachineDropIndex <.. MinidynDropIndex


class MachineReportThresholds {
  <<type>>
  | HeavydynReportThresholds   | MaxidynReportThresholds   | MinidynReportThresholds
}
MachineReportThresholds <.. HeavydynReportThresholds
MachineReportThresholds <.. MaxidynReportThresholds
MachineReportThresholds <.. MinidynReportThresholds


class MachineReportThresholdsGroups {
  <<type>>
  | HeavydynReportThresholdsGroups   | MaxidynReportThresholdsGroups   | MinidynReportThresholdsGroups
}
MachineReportThresholdsGroups <.. HeavydynReportThresholdsGroups
MachineReportThresholdsGroups <.. MaxidynReportThresholdsGroups
MachineReportThresholdsGroups <.. MinidynReportThresholdsGroups


class MachineTableDataLabelsParameters {
  <<type>>
  | HeavydynTableDataLabelsParameters   | MaxidynTableDataLabelsParameters   | MinidynTableDataLabelsParameters
}
MachineTableDataLabelsParameters <.. HeavydynTableDataLabelsParameters
MachineTableDataLabelsParameters <.. MaxidynTableDataLabelsParameters
MachineTableDataLabelsParameters <.. MinidynTableDataLabelsParameters


class MachineReportDataLabels {
  <<type>>
  | HeavydynReportDataLabels   | MaxidynReportDataLabels   | MinidynReportDataLabels
}
MachineReportDataLabels <.. HeavydynReportDataLabels
MachineReportDataLabels <.. MaxidynReportDataLabels
MachineReportDataLabels <.. MinidynReportDataLabels


class MachineReportCreatorParameters {
  <<interface>>
  project: MachineProject
}
MachineReportCreatorParameters <.. MachineProject


class JSONCustomThreshold {
  <<interface>>
  version: 1
  type: CustomThresholdType
  value: number
  valueHigh: number
}
JSONCustomThreshold <.. CustomThresholdType


class CustomThresholdType {
  <<type>>
  'Bicolor' | 'Gradient' | 'Tricolor'
}



class CustomThreshold {
  <<interface>>
  kind: 'custom'
  name: 'Custom'
  type: CustomThresholdType
  value: number
  valueHigh: number
  getColor: #40;     mathNumber: MathNumber,     colors: JSONThresholdColors   #41; =#62; string
  toJSON: #40;#41; =#62; JSONCustomThreshold
}
CustomThreshold <.. CustomThresholdType


class PredefinedThreshold {
  <<interface>>
  kind: 'predefined'
  name: string
  value: number
  getColor: #40;     mathNumber: MathNumber,     colors: JSONThresholdColors   #41; =#62; string
}



class AnyThreshold {
  <<type>>
  PredefinedThreshold | CustomThreshold
}
AnyThreshold <.. PredefinedThreshold
AnyThreshold <.. CustomThreshold


class JSONDistinctThresholdsConfiguration {
  <<interface>>
  version: 1
  selected: number
  custom: JSONCustomThreshold
}
JSONDistinctThresholdsConfiguration <.. JSONCustomThreshold


class PartialExtendedObject~BaseObject, MachineObject~ {
  <<type>>
  Required#60;BaseObject#62; &   Partial#60;Omit#60;MachineObject, keyof BaseObject#62;#62;
}



class WatcherHandler {
  <<interface>>
  add: #40;stop: #40;#41; =#62; void#41; =#62; void
  remove: #40;stop: #40;#41; =#62; void#41; =#62; void
  clean: #40;#41; =#62; void
  stops: #40;#40;#41; =#62; void#41;[]
}



class BaseZoneCreatorParameters {
  <<interface>>
  machine: MachineName
}
BaseZoneCreatorParameters <.. MachineName
MachineZoneCreatorParameters <|-- BaseZoneCreatorParameters

class JSONBaseZoneVAny {
  <<type>>
  JSONBaseZone
}
JSONBaseZoneVAny <.. JSONBaseZone


class JSONBaseZone {
  <<interface>>
  version: 1
  name: string
  points: JSONMachinePoint[]
  settings: JSONZoneSettings
}
JSONBaseZone <.. JSONMachinePoint
JSONBaseZone <.. JSONZoneSettings


class JSONZoneSettings {
  <<interface>>
  version: 1
  color: ColorName
  isVisible: boolean
}
JSONZoneSettings <.. ColorName


class BaseZone {
  <<interface>>
  machine: MachineName
  points: MachinePoint[]
  settings: JSONZoneSettings
  name: string
  report: MachineReport
  init: #40;#41; =#62; void
  clean: #40;#41; =#62; void
  toBaseJSON: #40;#41; =#62; JSONBaseZone
}
BaseZone <.. MachineName
BaseZone <.. MachinePoint
BaseZone <.. JSONZoneSettings
BaseZone <.. MachineReport


class HeavydynZoneCreatorParameters {
  <<interface>>
  report: HeavydynReport
}
HeavydynZoneCreatorParameters <.. HeavydynReport
MachineZoneCreatorParameters <|-- HeavydynZoneCreatorParameters

class JSONHeavydynZoneVAny {
  <<type>>
  JSONHeavydynZone
}
JSONHeavydynZoneVAny <.. JSONHeavydynZone


class JSONHeavydynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONHeavydynZoneDistinct
}
JSONHeavydynZone <.. JSONBaseZone
JSONHeavydynZone <.. JSONHeavydynZoneDistinct


class JSONHeavydynZoneDistinct {
  <<interface>>
  version: 1
}



class HeavydynZone {
  <<interface>>
  machine: 'Heavydyn'
  points: HeavydynPoint[]
  toJSON: #40;#41; =#62; JSONHeavydynZone
}

BaseZone <|-- HeavydynZone

class MaxidynZoneCreatorParameters {
  <<interface>>
  report: MaxidynReport
}
MaxidynZoneCreatorParameters <.. MaxidynReport
MachineZoneCreatorParameters <|-- MaxidynZoneCreatorParameters

class JSONMaxidynZoneVAny {
  <<type>>
  JSONMaxidynZone
}
JSONMaxidynZoneVAny <.. JSONMaxidynZone


class JSONMaxidynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONMaxidynZoneDistinct
}
JSONMaxidynZone <.. JSONBaseZone
JSONMaxidynZone <.. JSONMaxidynZoneDistinct


class JSONMaxidynZoneDistinct {
  <<interface>>
  version: 1
}



class MaxidynZone {
  <<interface>>
  machine: 'Maxidyn'
  points: MaxidynPoint[]
  toJSON: #40;#41; =#62; JSONMaxidynZone
}

BaseZone <|-- MaxidynZone

class MinidynZoneCreatorParameters {
  <<interface>>
  report: MinidynReport
}
MinidynZoneCreatorParameters <.. MinidynReport
MachineZoneCreatorParameters <|-- MinidynZoneCreatorParameters

class JSONMinidynZoneVAny {
  <<type>>
  JSONMinidynZone
}
JSONMinidynZoneVAny <.. JSONMinidynZone


class JSONMinidynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONMinidynZoneDistinct
}
JSONMinidynZone <.. JSONBaseZone
JSONMinidynZone <.. JSONMinidynZoneDistinct


class JSONMinidynZoneDistinct {
  <<interface>>
  version: 1
}



class MinidynZone {
  <<interface>>
  machine: 'Minidyn'
  points: MinidynPoint[]
  toJSON: #40;#41; =#62; JSONMinidynZone
}

BaseZone <|-- MinidynZone

class JSONMachineZone {
  <<type>>
  JSONHeavydynZone | JSONMaxidynZone | JSONMinidynZone
}
JSONMachineZone <.. JSONHeavydynZone
JSONMachineZone <.. JSONMaxidynZone
JSONMachineZone <.. JSONMinidynZone


class MachineZone {
  <<type>>
  HeavydynZone | MaxidynZone | MinidynZone
}
MachineZone <.. HeavydynZone
MachineZone <.. MaxidynZone
MachineZone <.. MinidynZone


class PartialMachineZone~MachineZone~ {
  <<type>>
  PartialExtendedObject#60;   BaseZone,   MachineZone #62;
}
PartialMachineZone~MachineZone~ <.. PartialExtendedObject~BaseObject, MachineObject~
PartialMachineZone~MachineZone~ <.. BaseZone
PartialMachineZone~MachineZone~ <.. MachineZone


class MachineZoneCreatorParameters {
  <<interface>>
  report: MachineReport
}
MachineZoneCreatorParameters <.. MachineReport


class ExcelData {
  <<type>>
  string | number | boolean
}



class ExcelFlatData {
  <<type>>
  string[] | number[] | boolean[]
}



class ExcelJson {
  <<interface>>
  [key: string]: ExcelData | ExcelFlatData
}
ExcelJson <.. ExcelData
ExcelJson <.. ExcelFlatData
AnyJSON <|-- ExcelJson

class FlatDataJson {
  <<interface>>
  [key: string]: ExcelFlatData
}
FlatDataJson <.. ExcelFlatData


class Exporter {
  <<interface>>
  name: string
  export: #40;...args: any[]#41; =#62; Promise#60;File#62;
}



class AnyExporter {
  <<type>>
  | MachineExporter   | HeavydynExporter   | MaxidynExporter   | MinidynExporter
}
AnyExporter <.. MachineExporter
AnyExporter <.. HeavydynExporter
AnyExporter <.. MaxidynExporter
AnyExporter <.. MinidynExporter


class MachineExporter {
  <<interface>>
  export: #40;project: MachineProject#41; =#62; Promise#60;File#62;
}

Exporter <|-- MachineExporter

class HeavydynExporter {
  <<interface>>
  export: #40;project: HeavydynProject#41; =#62; Promise#60;File#62;
}

Exporter <|-- HeavydynExporter

class MaxidynExporter {
  <<interface>>
  export: #40;project: MaxidynProject#41; =#62; Promise#60;File#62;
}

Exporter <|-- MaxidynExporter

class MinidynExporter {
  <<interface>>
  export: #40;project: MinidynProject#41; =#62; Promise#60;File#62;
}

Exporter <|-- MinidynExporter

class ImpactData {
  <<interface>>
  load: number[]
  displacement: number[][]
}



class LngLat {
  <<interface>>
  lng: number
  lat: number
}



class XYCoord {
  <<interface>>
  x: number
  y: number
}



class SelectableList~S, L~ {
  <<interface>>
  selected: S | null
  list: L[]
}



class DeepRequired~T~ {
  <<type>>
  #123;   [K in keyof T]: Required#60;DeepRequired#60;T[K]#62;#62; #125;
}
DeepRequired~T~ <.. DeepRequired~T~


class AnyJSON {
  <<interface>>
  [key: string]: any
}



class Store {
  <<interface>>
  projects: SelectableList#60;MachineProject#62;
  map: mapboxgl.Map | null
  updateAvailable: boolean
  save: #40;key: StoreKeys, value: StoreSaveableTypes#41; =#62; void
}
Store <.. SelectableList~S, L~
Store <.. MachineProject


class StoreKeys {
  <<type>>
  Exclude#60;keyof Store, 'save' | 'updateAvailable'#62;
}
StoreKeys <.. Store


class StoreTypes {
  <<type>>
  Store[keyof Store]
}
StoreTypes <.. Store


class StoreSaveableTypes {
  <<type>>
  Extract#60;   StoreTypes,   string[] | number[] | boolean[] | string | number | boolean | null #62;
}
StoreSaveableTypes <.. StoreTypes


