classDiagram
class JSONMaxidynDataLabelsGroup {
  <<type>>
  JSONMaxidynDataLabelsGroups[number]
}
JSONMaxidynDataLabelsGroup <.. JSONMaxidynDataLabelsGroups


class JSONMaxidynDataLabelsGroups {
  <<type>>
  [   JSONMaxidynDropDataLabelsGroup,   JSONMaxidynTestDataLabelsGroup,   JSONMaxidynZoneDataLabelsGroup ]
}
JSONMaxidynDataLabelsGroups <.. JSONMaxidynDropDataLabelsGroup
JSONMaxidynDataLabelsGroups <.. JSONMaxidynTestDataLabelsGroup
JSONMaxidynDataLabelsGroups <.. JSONMaxidynZoneDataLabelsGroup


class JSONMaxidynDropDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Drop', MaxidynUnitsNames#62;
  distinct: JSONMaxidynDropDataLabelsGroupDistinct
}
JSONMaxidynDropDataLabelsGroup <.. MaxidynUnitsNames
JSONMaxidynDropDataLabelsGroup <.. JSONMaxidynDropDataLabelsGroupDistinct


class JSONMaxidynDropDataLabelsGroupDistinct {
  <<interface>>
  version: 1
  indexes: JSONSelectableList#60;JSONMaxidynDropIndex#62;
}
JSONMaxidynDropDataLabelsGroupDistinct <.. JSONMaxidynDropIndex


class JSONMaxidynTestDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Test', MaxidynUnitsNames#62;
  distinct: #123;     readonly version: 1   #125;
}
JSONMaxidynTestDataLabelsGroup <.. MaxidynUnitsNames


class JSONMaxidynTestDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class JSONMaxidynZoneDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Zone', MaxidynUnitsNames#62;
  distinct: JSONMaxidynZoneDataLabelsGroupDistinct
}
JSONMaxidynZoneDataLabelsGroup <.. MaxidynUnitsNames
JSONMaxidynZoneDataLabelsGroup <.. JSONMaxidynZoneDataLabelsGroupDistinct


class JSONMaxidynZoneDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class MaxidynDataLabels {
  <<interface>>
  groups: SelectableList#60;     MaxidynDataLabelsGroup,     MaxidynDataLabelsGroups   #62;
}
MaxidynDataLabels <.. MaxidynDataLabelsGroup
MaxidynDataLabels <.. MaxidynDataLabelsGroups


class MaxidynDataLabelsGroup {
  <<type>>
  MaxidynDataLabelsGroups[number]
}
MaxidynDataLabelsGroup <.. MaxidynDataLabelsGroups


class MaxidynDataLabelsGroups {
  <<type>>
  [   MaxidynDropDataLabelsGroup,   MaxidynTestDataLabelsGroup,   MaxidynZoneDataLabelsGroup ]
}
MaxidynDataLabelsGroups <.. MaxidynDropDataLabelsGroup
MaxidynDataLabelsGroups <.. MaxidynTestDataLabelsGroup
MaxidynDataLabelsGroups <.. MaxidynZoneDataLabelsGroup


class MaxidynDropDataLabelsGroup {
  <<interface>>
  indexes: SelectableList#60;MaxidynDropIndex#62;
  toJSON: #40;#41; =#62; JSONMaxidynDropDataLabelsGroup
}
MaxidynDropDataLabelsGroup <.. MaxidynDropIndex


class MaxidynTestDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMaxidynTestDataLabelsGroup
}



class MaxidynZoneDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMaxidynZoneDataLabelsGroup
}



class JSONMaxidynDropVAny {
  <<type>>
  JSONMaxidynDrop
}
JSONMaxidynDropVAny <.. JSONMaxidynDrop


class JSONMaxidynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONMaxidynDropDistinct
}
JSONMaxidynDrop <.. JSONMaxidynDropDistinct


class JSONMaxidynDropDistinct {
  <<interface>>
  version: 1
}



class JSONMaxidynDropIndexVAny {
  <<type>>
  JSONMaxidynDropIndex
}
JSONMaxidynDropIndexVAny <.. JSONMaxidynDropIndex


class JSONMaxidynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONMaxidynDropIndexDistinct
}
JSONMaxidynDropIndex <.. JSONMaxidynDropIndexDistinct


class JSONMaxidynDropIndexDistinct {
  <<interface>>
  version: 1
  type: MaxidynDropType
}
JSONMaxidynDropIndexDistinct <.. MaxidynDropType


class MaxidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MaxidynDrop {
  <<interface>>

}



class MaxidynDropIndex {
  <<interface>>
  type: MaxidynDropType
}
MaxidynDropIndex <.. MaxidynDropType


class MaxidynUnitsSkeleton~A, B, C, D, E, F, G~ {
  <<interface>>
  modulus: A
  stiffness: B
  deflection: C
  force: D
  distance: E
  time: F
  percentage: G
}



class PossibleMaxidynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleMaxidynStiffnessUnits {
  <<type>>
  'MN / m'
}



class PossibleMaxidynDeflectionUnits {
  <<type>>
  'mm' | 'um'
}



class PossibleMaxidynForceUnits {
  <<type>>
  'N' | 'kN'
}



class PossibleMaxidynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleMaxidynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleMaxidynPercentageUnits {
  <<type>>
  '%'
}



class JSONMaxidynUnits {
  <<type>>
  MaxidynUnitsSkeleton#60;   JSONMathUnit#60;PossibleMaxidynModulusUnits#62;,   JSONMathUnit#60;PossibleMaxidynStiffnessUnits#62;,   JSONMathUnit#60;PossibleMaxidynDeflectionUnits#62;,   JSONMathUnit#60;PossibleMaxidynForceUnits#62;,   JSONMathUnit#60;PossibleMaxidynDistanceUnits#62;,   JSONMathUnit#60;PossibleMaxidynTimeUnits#62;,   JSONMathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
JSONMaxidynUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
JSONMaxidynUnits <.. PossibleMaxidynModulusUnits
JSONMaxidynUnits <.. PossibleMaxidynStiffnessUnits
JSONMaxidynUnits <.. PossibleMaxidynDeflectionUnits
JSONMaxidynUnits <.. PossibleMaxidynForceUnits
JSONMaxidynUnits <.. PossibleMaxidynDistanceUnits
JSONMaxidynUnits <.. PossibleMaxidynTimeUnits
JSONMaxidynUnits <.. PossibleMaxidynPercentageUnits


class MaxidynMathUnits {
  <<type>>
  MaxidynUnitsSkeleton#60;   MathUnit#60;PossibleMaxidynModulusUnits#62;,   MathUnit#60;PossibleMaxidynStiffnessUnits#62;,   MathUnit#60;PossibleMaxidynDeflectionUnits#62;,   MathUnit#60;PossibleMaxidynForceUnits#62;,   MathUnit#60;PossibleMaxidynDistanceUnits#62;,   MathUnit#60;PossibleMaxidynTimeUnits#62;,   MathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
MaxidynMathUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MaxidynMathUnits <.. PossibleMaxidynModulusUnits
MaxidynMathUnits <.. PossibleMaxidynStiffnessUnits
MaxidynMathUnits <.. PossibleMaxidynDeflectionUnits
MaxidynMathUnits <.. PossibleMaxidynForceUnits
MaxidynMathUnits <.. PossibleMaxidynDistanceUnits
MaxidynMathUnits <.. PossibleMaxidynTimeUnits
MaxidynMathUnits <.. PossibleMaxidynPercentageUnits


class MaxidynUnitsNames {
  <<type>>
  keyof MaxidynUnitsSkeleton#60;any#62;
}
MaxidynUnitsNames <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class JSONMaxidynPointVAny {
  <<type>>
  JSONMaxidynPoint
}
JSONMaxidynPointVAny <.. JSONMaxidynPoint


class JSONMaxidynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONMaxidynPointDistinct
}
JSONMaxidynPoint <.. JSONMaxidynPointDistinct


class JSONMaxidynPointDistinct {
  <<interface>>
  version: 1
}



class MaxidynPoint {
  <<interface>>

}



class JSONMaxidynProjectVAny {
  <<type>>
  JSONMaxidynProject
}
JSONMaxidynProjectVAny <.. JSONMaxidynProject


class JSONMaxidynProject {
  <<interface>>
  version: 1
  machine: 'Maxidyn'
  base: JSONBaseProject
  distinct: JSONMaxidynProjectDistinct
}
JSONMaxidynProject <.. JSONMaxidynProjectDistinct


class JSONMaxidynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONMaxidynUnits
  bearingParameters: JSONBearingParameters
}
JSONMaxidynProjectDistinct <.. JSONMaxidynUnits


class MaxidynProject {
  <<interface>>
  bearingParameters: JSONBearingParameters
}



class MaxidynReportCreatorParameters {
  <<interface>>
  project: MaxidynProject
}
MaxidynReportCreatorParameters <.. MaxidynProject


class JSONMaxidynReportVAny {
  <<type>>
  JSONMaxidynReport
}
JSONMaxidynReportVAny <.. JSONMaxidynReport


class JSONMaxidynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONMaxidynReportDistinct
}
JSONMaxidynReport <.. JSONMaxidynReportDistinct


class JSONMaxidynReportDistinct {
  <<interface>>
  version: 1
  dataLabels: JSONSelectableList#60;     JSONMaxidynDataLabelsGroup,     JSONMaxidynDataLabelsGroups   #62;
  thresholds: JSONMaxidynThresholdsConfigurations
}
JSONMaxidynReportDistinct <.. JSONMaxidynDataLabelsGroup
JSONMaxidynReportDistinct <.. JSONMaxidynDataLabelsGroups
JSONMaxidynReportDistinct <.. JSONMaxidynThresholdsConfigurations


class JSONMaxidynThresholdsConfigurations {
  <<type>>
  MaxidynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONMaxidynThresholdsConfigurations <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class MaxidynReport {
  <<interface>>
  addZone: #40;#41; =#62; void
}



class MaxidynThresholds {
  <<interface>>
  groups: MaxidynThresholdsGroups
}
MaxidynThresholds <.. MaxidynThresholdsGroups


class MaxidynThresholdsGroups {
  <<type>>
  MaxidynUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}
MaxidynThresholdsGroups <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class MaxidynObject~T~ {
  <<interface>>

}



class MaxidynZoneCreatorParameters {
  <<interface>>
  report: MaxidynReport
}
MaxidynZoneCreatorParameters <.. MaxidynReport


class JSONMaxidynZoneVAny {
  <<type>>
  JSONMaxidynZone
}
JSONMaxidynZoneVAny <.. JSONMaxidynZone


class JSONMaxidynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONMaxidynZoneDistinct
}
JSONMaxidynZone <.. JSONMaxidynZoneDistinct


class JSONMaxidynZoneDistinct {
  <<interface>>
  version: 1
}



class MaxidynZone {
  <<interface>>

}



class MaxidynExporter {
  <<interface>>
  export: #40;project: MaxidynProject#41; =#62; Promise#60;File#62;
}



