classDiagram
class MinidynField {
  <<interface>>

}



class MinidynPoint {
  <<interface>>
  machine: 'Minidyn'
}



class MinidynProject {
  <<interface>>
  machine: 'Minidyn'
  reports: SelectableList#60;MinidynReport#62;
}
MinidynProject <.. MinidynReport


class MinidynUnits {
  <<interface>>
  modulus: MathUnit
  deformation: MathUnit
  force: MathUnit
  temperature: MathUnit
}



class JSONMinidynUnits {
  <<interface>>
  modulus: 'MPa' | 'kN'
  deformation: 'mm' | 'um'
  force: 'N' | 'kN'
}



class MinidynReport {
  <<interface>>
  machine: 'Minidyn'
  points: MinidynPoint[]
  platform: MinidynField[]
  informations: MinidynField[]
}
MinidynReport <.. MinidynPoint
MinidynReport <.. MinidynField


class MinidynReportCreatorParameters {
  <<interface>>
  units: MinidynUnits
}
MinidynReportCreatorParameters <.. MinidynUnits


class MinidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MinidynDropIndex {
  <<interface>>
  machine: 'Minidyn'
  type: MinidynDropType
}
MinidynDropIndex <.. MinidynDropType


