classDiagram
class JSONHeavydynDataLabelsGroup {
  <<type>>
  JSONHeavydynDataLabelsGroups[number]
}
JSONHeavydynDataLabelsGroup <.. JSONHeavydynDataLabelsGroups


class JSONHeavydynDataLabelsGroups {
  <<type>>
  [   JSONHeavydynDropDataLabelsGroup,   JSONHeavydynTestDataLabelsGroup,   JSONHeavydynZoneDataLabelsGroup ]
}
JSONHeavydynDataLabelsGroups <.. JSONHeavydynDropDataLabelsGroup
JSONHeavydynDataLabelsGroups <.. JSONHeavydynTestDataLabelsGroup
JSONHeavydynDataLabelsGroups <.. JSONHeavydynZoneDataLabelsGroup


class JSONHeavydynDropDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Drop', HeavydynUnitsNames#62;
  distinct: JSONHeavydynDropDataLabelsGroupDistinct
}
JSONHeavydynDropDataLabelsGroup <.. HeavydynUnitsNames
JSONHeavydynDropDataLabelsGroup <.. JSONHeavydynDropDataLabelsGroupDistinct


class JSONHeavydynDropDataLabelsGroupDistinct {
  <<interface>>
  version: 1
  indexes: JSONSelectableList#60;JSONHeavydynDropIndex#62;
  sequenceName: string
}
JSONHeavydynDropDataLabelsGroupDistinct <.. JSONHeavydynDropIndex


class JSONHeavydynTestDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Test', HeavydynUnitsNames#62;
  distinct: #123;     readonly version: 1   #125;
}
JSONHeavydynTestDataLabelsGroup <.. HeavydynUnitsNames


class JSONHeavydynTestDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class JSONHeavydynZoneDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Zone', HeavydynUnitsNames#62;
  distinct: JSONHeavydynZoneDataLabelsGroupDistinct
}
JSONHeavydynZoneDataLabelsGroup <.. HeavydynUnitsNames
JSONHeavydynZoneDataLabelsGroup <.. JSONHeavydynZoneDataLabelsGroupDistinct


class JSONHeavydynZoneDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class HeavydynDataLabels {
  <<interface>>
  groups: SelectableList#60;     HeavydynDataLabelsGroup,     HeavydynDataLabelsGroups   #62;
}
HeavydynDataLabels <.. HeavydynDataLabelsGroup
HeavydynDataLabels <.. HeavydynDataLabelsGroups


class HeavydynDataLabelsGroup {
  <<type>>
  HeavydynDataLabelsGroups[number]
}
HeavydynDataLabelsGroup <.. HeavydynDataLabelsGroups


class HeavydynDataLabelsGroups {
  <<type>>
  [   HeavydynDropDataLabelsGroup,   HeavydynTestDataLabelsGroup,   HeavydynZoneDataLabelsGroup ]
}
HeavydynDataLabelsGroups <.. HeavydynDropDataLabelsGroup
HeavydynDataLabelsGroups <.. HeavydynTestDataLabelsGroup
HeavydynDataLabelsGroups <.. HeavydynZoneDataLabelsGroup


class HeavydynDropDataLabelsGroup {
  <<interface>>
  indexes: SelectableList#60;HeavydynDropIndex#62;
  sequenceName: string
  toJSON: #40;#41; =#62; JSONHeavydynDropDataLabelsGroup
}
HeavydynDropDataLabelsGroup <.. HeavydynDropIndex


class HeavydynTestDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONHeavydynTestDataLabelsGroup
}



class HeavydynZoneDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONHeavydynZoneDataLabelsGroup
}



class JSONHeavydynDropVAny {
  <<type>>
  JSONHeavydynDrop
}
JSONHeavydynDropVAny <.. JSONHeavydynDrop


class JSONHeavydynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONHeavydynDropDistinct
}
JSONHeavydynDrop <.. JSONHeavydynDropDistinct


class JSONHeavydynDropDistinct {
  <<interface>>
  version: 1
}



class JSONHeavydynDropIndexVAny {
  <<type>>
  JSONHeavydynDropIndex
}
JSONHeavydynDropIndexVAny <.. JSONHeavydynDropIndex


class JSONHeavydynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONHeavydynDropIndexDistinct
}
JSONHeavydynDropIndex <.. JSONHeavydynDropIndexDistinct


class JSONHeavydynDropIndexDistinct {
  <<interface>>
  version: 1
  type: HeavydynDropType
  value: number
  unit: string
}
JSONHeavydynDropIndexDistinct <.. HeavydynDropType


class HeavydynDropType {
  <<type>>
  'Distance' | 'Time' | 'Force' | 'Height'
}



class HeavydynDrop {
  <<interface>>

}



class HeavydynDropIndex {
  <<interface>>
  type: HeavydynDropType
  value: MathNumber
}
HeavydynDropIndex <.. HeavydynDropType


class HeavydynUnitsSkeleton~A, B, C, D, E~ {
  <<interface>>
  deflection: A
  force: B
  temperature: C
  distance: D
  time: E
}



class HeavydynUnitsNames {
  <<type>>
  keyof HeavydynUnitsSkeleton#60;any#62;
}
HeavydynUnitsNames <.. HeavydynUnitsSkeleton~A, B, C, D, E~


class PossibleHeavydynDeflectionUnits {
  <<type>>
  'mm' | '1/100 mm' | 'um'
}



class PossibleHeavydynForceUnits {
  <<type>>
  'N' | 'kN' | 'lbs'
}



class PossibleHeavydynTemperatureUnits {
  <<type>>
  '°C' | '°F' | 'K'
}



class PossibleHeavydynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleHeavydynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class JSONHeavydynUnits {
  <<type>>
  HeavydynUnitsSkeleton#60;   JSONMathUnit#60;PossibleHeavydynDeflectionUnits#62;,   JSONMathUnit#60;PossibleHeavydynForceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTemperatureUnits#62;,   JSONMathUnit#60;PossibleHeavydynDistanceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTimeUnits#62; #62;
}
JSONHeavydynUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E~
JSONHeavydynUnits <.. PossibleHeavydynDeflectionUnits
JSONHeavydynUnits <.. PossibleHeavydynForceUnits
JSONHeavydynUnits <.. PossibleHeavydynTemperatureUnits
JSONHeavydynUnits <.. PossibleHeavydynDistanceUnits
JSONHeavydynUnits <.. PossibleHeavydynTimeUnits


class HeavydynMathUnits {
  <<type>>
  HeavydynUnitsSkeleton#60;   MathUnit#60;PossibleHeavydynDeflectionUnits#62;,   MathUnit#60;PossibleHeavydynForceUnits#62;,   MathUnit#60;PossibleHeavydynTemperatureUnits#62;,   MathUnit#60;PossibleHeavydynDistanceUnits#62;,   MathUnit#60;PossibleHeavydynTimeUnits#62; #62;
}
HeavydynMathUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E~
HeavydynMathUnits <.. PossibleHeavydynDeflectionUnits
HeavydynMathUnits <.. PossibleHeavydynForceUnits
HeavydynMathUnits <.. PossibleHeavydynTemperatureUnits
HeavydynMathUnits <.. PossibleHeavydynDistanceUnits
HeavydynMathUnits <.. PossibleHeavydynTimeUnits


class JSONHeavydynPointVAny {
  <<type>>
  JSONHeavydynPoint
}
JSONHeavydynPointVAny <.. JSONHeavydynPoint


class JSONHeavydynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONHeavydynPointDistinct
}
JSONHeavydynPoint <.. JSONHeavydynPointDistinct


class JSONHeavydynPointDistinct {
  <<interface>>
  version: 1
}



class HeavydynPoint {
  <<interface>>

}



class JSONHeavydynProjectVAny {
  <<type>>
  JSONHeavydynProject
}
JSONHeavydynProjectVAny <.. JSONHeavydynProject


class JSONHeavydynProject {
  <<interface>>
  version: 1
  machine: 'Heavydyn'
  base: JSONBaseProject
  distinct: JSONHeavydynProjectDistinct
}
JSONHeavydynProject <.. JSONHeavydynProjectDistinct


class JSONHeavydynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONHeavydynUnits
  calibrations: JSONHeavydynCalibrations
  correctionParameters: JSONHeavydynCorrectionParameters
}
JSONHeavydynProjectDistinct <.. JSONHeavydynUnits
JSONHeavydynProjectDistinct <.. JSONHeavydynCalibrations
JSONHeavydynProjectDistinct <.. JSONHeavydynCorrectionParameters


class JSONHeavydynCalibrations {
  <<interface>>
  version: 1
  date: string
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}



class JSONHeavydynCorrectionParameters {
  <<interface>>
  version: 1
  load: #123;     readonly version: 1     readonly active: boolean     readonly loadReferenceSource: LoadReferenceSourceValue     readonly customValue: number   #125;
  temperature: #123;     readonly version: 1     readonly active: boolean     readonly temperatureFromSource: TemperatureFromSourceValue     readonly average: TemperatureAverageValue     readonly customValue: number     readonly temperatureTo: number     readonly structureType: number   #125;
}



class HeavydynProject {
  <<interface>>
  calibrations: HeavydynCalibrations
  correctionParameters: HeavydynCorrectionParameters
}
HeavydynProject <.. HeavydynCalibrations
HeavydynProject <.. HeavydynCorrectionParameters


class HeavydynCalibrations {
  <<interface>>
  date: Date
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}



class HeavydynCorrectionParameters {
  <<interface>>
  load: #123;     active: boolean     loadReferenceSource: SelectableList#60;       LoadReferenceSourceValue,       LoadReferenceSourceList     #62;     customValue: MathNumber   #125;
  temperature: #123;     active: boolean     temperatureFromSource: SelectableList#60;       TemperatureFromSourceValue,       TemperatureFromSourceList     #62;     average: SelectableList#60;TemperatureAverageValue, TemperatureAverageList#62;     customValue: MathNumber     temperatureTo: MathNumber     structureType: SelectableList#60;       TemperatureStructureTypeValue,       TemperatureStructureTypeList     #62;   #125;
}



class HeavydynReportCreatorParameters {
  <<interface>>
  project: HeavydynProject
}
HeavydynReportCreatorParameters <.. HeavydynProject


class JSONHeavydynReportVAny {
  <<type>>
  JSONHeavydynReport
}
JSONHeavydynReportVAny <.. JSONHeavydynReport


class JSONHeavydynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONHeavydynReportDistinct
}
JSONHeavydynReport <.. JSONHeavydynReportDistinct


class JSONHeavydynReportDistinct {
  <<interface>>
  version: 1
  dataLabels: JSONSelectableList#60;     JSONHeavydynDataLabelsGroup,     JSONHeavydynDataLabelsGroups   #62;
  thresholds: JSONHeavydynThresholdsConfigurations
}
JSONHeavydynReportDistinct <.. JSONHeavydynDataLabelsGroup
JSONHeavydynReportDistinct <.. JSONHeavydynDataLabelsGroups
JSONHeavydynReportDistinct <.. JSONHeavydynThresholdsConfigurations


class JSONHeavydynThresholdsConfigurations {
  <<type>>
  HeavydynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONHeavydynThresholdsConfigurations <.. HeavydynUnitsSkeleton~A, B, C, D, E~


class HeavydynReport {
  <<interface>>
  addZone: #40;#41; =#62; void
}



class HeavydynThresholds {
  <<interface>>
  groups: HeavydynThresholdsGroups
}
HeavydynThresholds <.. HeavydynThresholdsGroups


class HeavydynThresholdsGroups {
  <<type>>
  HeavydynUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}
HeavydynThresholdsGroups <.. HeavydynUnitsSkeleton~A, B, C, D, E~


class HeavydynObject~T~ {
  <<interface>>

}



class HeavydynZoneCreatorParameters {
  <<interface>>
  report: HeavydynReport
}
HeavydynZoneCreatorParameters <.. HeavydynReport


class JSONHeavydynZoneVAny {
  <<type>>
  JSONHeavydynZone
}
JSONHeavydynZoneVAny <.. JSONHeavydynZone


class JSONHeavydynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONHeavydynZoneDistinct
}
JSONHeavydynZone <.. JSONHeavydynZoneDistinct


class JSONHeavydynZoneDistinct {
  <<interface>>
  version: 1
}



class HeavydynZone {
  <<interface>>

}



class HeavydynExporter {
  <<interface>>
  export: #40;project: HeavydynProject#41; =#62; Promise#60;File#62;
}



