/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconHeroiconsOutlineDocumentAdd: typeof import('~icons/heroicons-outline/document-add')['default']
    IconHeroiconsSolidCheck: typeof import('~icons/heroicons-solid/check')['default']
    IconHeroiconsSolidChevronDown: typeof import('~icons/heroicons-solid/chevron-down')['default']
    IconHeroiconsSolidChevronRight: typeof import('~icons/heroicons-solid/chevron-right')['default']
    IconHeroiconsSolidExclamationCircle: typeof import('~icons/heroicons-solid/exclamation-circle')['default']
    IconHeroiconsSolidSelector: typeof import('~icons/heroicons-solid/selector')['default']
    IconTablerBrandGitlab: typeof import('~icons/tabler/brand-gitlab')['default']
  }
}
