// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Button2: typeof import('./components/Generics/Button2.vue')['default']
    Container: typeof import('./components/Generics/Container.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DialogInformations: typeof import('./components/DialogInformations.vue')['default']
    Disclosure: typeof import('./components/Disclosure.vue')['default']
    Divider: typeof import('./components/Divider.vue')['default']
    DragAndDrop: typeof import('./components/DragAndDrop.vue')['default']
    IconHeroiconsOutlineDocumentAdd: typeof import('~icons/heroicons-outline/document-add')['default']
    IconHeroiconsSolidCheck: typeof import('~icons/heroicons-solid/check')['default']
    IconHeroiconsSolidChevronDown: typeof import('~icons/heroicons-solid/chevron-down')['default']
    IconHeroiconsSolidChevronRight: typeof import('~icons/heroicons-solid/chevron-right')['default']
    IconHeroiconsSolidExclamationCircle: typeof import('~icons/heroicons-solid/exclamation-circle')['default']
    IconHeroiconsSolidSelector: typeof import('~icons/heroicons-solid/selector')['default']
    IconTablerBrandGitlab: typeof import('~icons/tabler/brand-gitlab')['default']
    Illustration: typeof import('./components/Generics/Illustration.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Input2: typeof import('./components/Generics/Input2.vue')['default']
    Label: typeof import('./components/Label.vue')['default']
    Listbox: typeof import('./components/Listbox.vue')['default']
    ListboxColors: typeof import('./components/ListboxColors.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    TransitionDropdown: typeof import('./components/TransitionDropdown.vue')['default']
  }
}

export {}
