classDiagram
class Color {
  <<type>>
  | 'black'   | 'white'   | 'gray'   | 'red'   | 'orange'   | 'amber'   | 'yellow'   | 'lime'   | 'green'   | 'emerald'   | 'teal'   | 'cyan'   | 'sky'   | 'blue'   | 'indigo'   | 'violet'   | 'purple'   | 'fuchsia'   | 'pink'   | 'rose'
}



class MachineField {
  <<type>>
  HeavydynField | MaxidynField | MinidynField
}



class IconName {
  <<type>>
  | 'circle'   | 'triangle'   | 'square'   | 'rhombus'   | 'flare'   | 'pentagon'   | 'hexagon'   | 'hexagonAlt'   | 'heptagon'   | 'octagon'
}



class MachinePoint {
  <<type>>
  HeavydynPoint | MaxidynPoint | MinidynPoint
}



class PartialMachinePoint~MachinePoint~ {
  <<type>>
  PartialExtendedObject#60;   BasePoint,   MachinePoint #62;
}
PartialMachinePoint~MachinePoint~ <.. MachinePoint


class MachineName {
  <<type>>
  'Heavydyn' | 'Maxidyn' | 'Minidyn'
}



class PointsState {
  <<type>>
  'value' | 'number' | 'nothing'
}



class MachineProject {
  <<type>>
  HeavydynProject | MaxidynProject | MinidynProject
}



class PartialMachineProject~MachineProject~ {
  <<type>>
  PartialExtendedObject#60;   BaseProject,   MachineProject #62;
}
PartialMachineProject~MachineProject~ <.. MachineProject


class JSONUnits {
  <<type>>
  JSONHeavydynUnits | JSONMaxidynUnits | JSONMinidynUnits
}



class MachineUnits {
  <<type>>
  HeavydynUnits | MaxidynUnits | MinidynUnits
}



class DataLabelsFrom {
  <<type>>
  'Drop' | 'Test' | 'Zone'
}



class HeavydynDropType {
  <<type>>
  'Distance' | 'Force' | 'Time'
}



class MaxidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MinidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MachineReport {
  <<type>>
  HeavydynReport | MaxidynReport | MinidynReport
}



class PartialMachineReport~MachineReport~ {
  <<type>>
  PartialExtendedObject#60;   BaseReport,   MachineReport #62;
}
PartialMachineReport~MachineReport~ <.. MachineReport


class MachineDropIndex {
  <<type>>
  HeavydynDropIndex | MaxidynDropIndex | MinidynDropIndex
}



class JSONMachineDropIndex {
  <<type>>
  | JSONHeavydynDropIndex   | MaxidynDropIndex   | MinidynDropIndex
}



class PartialExtendedObject~BaseObject, MachineObject~ {
  <<type>>
  Required#60;BaseObject#62; &   Partial#60;Omit#60;MachineObject, keyof BaseObject#62;#62;
}



class DeepRequired~T~ {
  <<type>>
  #123;   [K in keyof T]: Required#60;DeepRequired#60;T[K]#62;#62; #125;
}



class StoreKeys {
  <<type>>
  Exclude#60;keyof Store, 'save'#62;
}



class StoreTypes {
  <<type>>
  Store[keyof Store]
}



class StoreSaveableTypes {
  <<type>>
  Extract#60;   StoreTypes,   string[] | number[] | boolean[] | string | number | boolean | null #62;
}
StoreSaveableTypes <.. StoreTypes


